name: kravhantering-otel-dev

services:
  otel-lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "${OTEL_GRAFANA_HOST_PORT:-3300}:3000"
      - "${OTEL_GRPC_HOST_PORT:-4317}:4317"
      - "${OTEL_HTTP_HOST_PORT:-4318}:4318"
    volumes:
      - ./dev/grafana/provisioning/dashboard-provider.yml:/otel-lgtm/grafana/conf/provisioning/dashboards/kravhantering.yml:ro
      - ./dev/grafana/provisioning/dashboards:/otel-lgtm/grafana/conf/provisioning/dashboards/custom:ro

