import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer'
import type {
  DataSubjectExportItem,
  DataSubjectExportV1,
  DataSubjectExportValue,
} from '@/lib/privacy/data-subject-export-types'
import { formatActorDisplayNameForLocale } from '@/lib/privacy/display-name'

interface ComponentProps {
  exportData: DataSubjectExportV1
  locale: string
}

const labels = {
  en: {
    field: 'Field',
    generated: 'Generated',
    generatedBy: 'Generated by',
    limitationTitle: 'Limitations',
    noValue: 'Not available',
    object: 'Object',
    pageTitle: 'Data portability export',
    relation: 'Relation',
    source: 'Source',
    summary: 'Summary',
    timestamp: 'Timestamp',
    value: 'Value',
  },
  sv: {
    field: 'Fält',
    generated: 'Skapad',
    generatedBy: 'Skapad av',
    limitationTitle: 'Begränsningar',
    noValue: 'Saknas',
    object: 'Objekt',
    pageTitle: 'Dataportabilitetsexport',
    relation: 'Relation',
    source: 'Källa',
    summary: 'Sammanfattning',
    timestamp: 'Tidpunkt',
    value: 'Värde',
  },
} as const

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: '#1e293b',
  },
  title: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 6,
  },
  meta: {
    color: '#64748b',
    marginBottom: 3,
  },
  section: {
    marginTop: 14,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 6,
  },
  sourceBox: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 4,
    padding: 8,
    marginBottom: 8,
  },
  sourceTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  item: {
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 5,
    marginTop: 5,
  },
  row: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 2,
  },
  label: {
    width: 76,
    fontFamily: 'Helvetica-Bold',
    color: '#475569',
  },
  value: {
    flex: 1,
  },
  limitation: {
    marginBottom: 4,
  },
})

function localeLabels(locale: string) {
  return locale === 'en' ? labels.en : labels.sv
}

function itemValue(
  item: DataSubjectExportItem,
  value: DataSubjectExportValue,
  locale: string,
): string {
  if (value == null) return localeLabels(locale).noValue
  if (Array.isArray(value)) return value.join(', ')
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  const stringified = String(value)
  if (
    item.fieldName.toLowerCase().includes('display') ||
    item.fieldName.toLowerCase().includes('name') ||
    item.fieldName.endsWith('_by')
  ) {
    return formatActorDisplayNameForLocale(stringified, locale) ?? stringified
  }
  return stringified
}

function MetadataRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  )
}

function itemKey(item: DataSubjectExportItem): string {
  return [
    item.sourceKey,
    item.table,
    item.relatedObject?.type ?? 'no-object',
    item.relatedObject?.key ?? 'no-key',
    item.fieldName,
    item.timestamp ?? 'no-timestamp',
  ].join(':')
}

export default function DataSubjectExportPdfRenderer({
  exportData,
  locale,
}: ComponentProps) {
  const t = localeLabels(locale)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{t.pageTitle}</Text>
        <Text style={styles.meta}>{exportData.schemaVersion}</Text>
        <Text style={styles.meta}>
          {t.generated}: {exportData.generatedAt}
        </Text>
        <Text style={styles.meta}>HSA-ID: {exportData.subject.hsaId}</Text>
        <Text style={styles.meta}>
          Fingerprint: {exportData.subject.targetFingerprint}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{t.summary}</Text>
          <MetadataRow
            label={t.source}
            value={String(exportData.summary.sourceCount)}
          />
          <MetadataRow
            label={t.field}
            value={String(exportData.summary.itemCount)}
          />
          <MetadataRow
            label={t.generatedBy}
            value={`${exportData.generatedBy.displayName} (${exportData.generatedBy.hsaId})`}
          />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{t.source}</Text>
          {exportData.sources.map(source => (
            <View key={source.key} style={styles.sourceBox}>
              <Text style={styles.sourceTitle}>{source.key}</Text>
              <Text style={styles.meta}>
                {source.table} / {source.relationToSubject}
              </Text>
              {source.items.map(entry => (
                <View key={itemKey(entry)} style={styles.item}>
                  <MetadataRow label={t.field} value={entry.fieldName} />
                  <MetadataRow
                    label={t.value}
                    value={itemValue(entry, entry.value, locale)}
                  />
                  <MetadataRow
                    label={t.relation}
                    value={entry.relationToSubject}
                  />
                  {entry.relatedObject ? (
                    <MetadataRow
                      label={t.object}
                      value={
                        entry.relatedObject.label ??
                        `${entry.relatedObject.type}:${entry.relatedObject.key}`
                      }
                    />
                  ) : null}
                  {entry.timestamp ? (
                    <MetadataRow label={t.timestamp} value={entry.timestamp} />
                  ) : null}
                </View>
              ))}
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{t.limitationTitle}</Text>
          {exportData.limitations.map(limitation => (
            <Text key={limitation.key} style={styles.limitation}>
              {limitation.key}: {limitation.description}
            </Text>
          ))}
        </View>
      </Page>
    </Document>
  )
}
