import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer'
import type {
  AccessReviewActor,
  AccessReviewDecision,
  AccessReviewExportV1,
  AccessReviewRunStatus,
} from '@/lib/access-review/types'
import { formatActorDisplayNameForLocale } from '@/lib/privacy/display-name'

interface ComponentProps {
  exportData: AccessReviewExportV1
  locale: string
}

const labels = {
  en: {
    ai: 'AI',
    completed: 'Completed',
    decidedBy: 'Decided by',
    decision: 'Decision',
    due: 'Due',
    evidence: 'External evidence',
    generated: 'Generated',
    generatedBy: 'Generated by',
    limitationTitle: 'Limitations',
    permission: 'Permission',
    principal: 'Principal',
    reviewer: 'Reviewer',
    scope: 'Scope',
    source: 'Source',
    status: 'Status',
    summary: 'Summary',
    title: 'Access review export',
  },
  sv: {
    ai: 'AI',
    completed: 'Slutförd',
    decidedBy: 'Beslutad av',
    decision: 'Beslut',
    due: 'Förfaller',
    evidence: 'Extern evidens',
    generated: 'Skapad',
    generatedBy: 'Skapad av',
    limitationTitle: 'Begränsningar',
    permission: 'Behörighet',
    principal: 'Behörig',
    reviewer: 'Granskare',
    scope: 'Omfattning',
    source: 'Källa',
    status: 'Status',
    summary: 'Sammanfattning',
    title: 'Export av behörighetsöversyn',
  },
} as const

const decisionLabels: Record<
  'en' | 'sv',
  Record<AccessReviewDecision, string>
> = {
  en: {
    approved: 'Approved',
    changed: 'Changed',
    not_applicable: 'Not applicable',
    pending: 'Not saved',
    revoke_required: 'Revoke required',
  },
  sv: {
    approved: 'Godkänd',
    changed: 'Ändrad',
    not_applicable: 'Ej tillämplig',
    pending: 'Ej sparad',
    revoke_required: 'Återkalla',
  },
}

const statusLabels: Record<
  'en' | 'sv',
  Record<AccessReviewRunStatus, string>
> = {
  en: {
    cancelled: 'Cancelled',
    completed: 'Completed',
    draft: 'Draft',
    in_review: 'In review',
  },
  sv: {
    cancelled: 'Avbruten',
    completed: 'Slutförd',
    draft: 'Utkast',
    in_review: 'Pågår',
  },
}

const styles = StyleSheet.create({
  item: {
    borderTopColor: '#e2e8f0',
    borderTopWidth: 1,
    marginTop: 5,
    paddingTop: 5,
  },
  label: {
    color: '#475569',
    fontFamily: 'Helvetica-Bold',
    width: 82,
  },
  limitation: {
    marginBottom: 4,
  },
  meta: {
    color: '#64748b',
    marginBottom: 3,
  },
  page: {
    color: '#1e293b',
    fontFamily: 'Helvetica',
    fontSize: 9,
    padding: 36,
  },
  row: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 2,
  },
  section: {
    marginTop: 14,
  },
  sectionTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 12,
    marginBottom: 6,
  },
  sourceBox: {
    borderColor: '#e2e8f0',
    borderRadius: 4,
    borderWidth: 1,
    marginBottom: 8,
    padding: 8,
  },
  sourceTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 10,
    marginBottom: 4,
  },
  title: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 18,
    marginBottom: 6,
  },
  value: {
    flex: 1,
  },
})

function localeLabels(locale: string) {
  return locale === 'en' ? labels.en : labels.sv
}

function localeKey(locale: string): 'en' | 'sv' {
  return locale === 'en' ? 'en' : 'sv'
}

function MetadataRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  )
}

function actorLabel(actor: AccessReviewActor, locale: string): string {
  const displayName =
    formatActorDisplayNameForLocale(actor.displayName, locale) ??
    actor.displayName
  return `${displayName} (${actor.hsaId})`
}

export default function AccessReviewExportPdfRenderer({
  exportData,
  locale,
}: ComponentProps) {
  const t = localeLabels(locale)
  const localeName = localeKey(locale)
  const { run } = exportData

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{t.title}</Text>
        <Text style={styles.meta}>{exportData.schemaVersion}</Text>
        <Text style={styles.meta}>
          {t.generated}: {exportData.generatedAt}
        </Text>
        <Text style={styles.meta}>
          {t.generatedBy}: {actorLabel(exportData.generatedBy, locale)}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{t.summary}</Text>
          <MetadataRow label="ID" value={String(run.id)} />
          <MetadataRow
            label={t.status}
            value={statusLabels[localeName][run.status]}
          />
          <MetadataRow label={t.due} value={run.dueAt} />
          <MetadataRow
            label={t.reviewer}
            value={actorLabel(run.reviewer, locale)}
          />
          <MetadataRow
            label={t.evidence}
            value={run.externalEvidenceReference ?? '-'}
          />
          <MetadataRow
            label={t.decision}
            value={`${run.summary.itemCount - run.summary.pendingCount}/${run.summary.itemCount}`}
          />
          {run.completedAt ? (
            <MetadataRow label={t.completed} value={run.completedAt} />
          ) : null}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{t.permission}</Text>
          {exportData.items.map(item => (
            <View key={item.id} style={styles.sourceBox}>
              <Text style={styles.sourceTitle}>
                {item.scope.label} / {item.permissionType}
              </Text>
              <MetadataRow
                label={t.principal}
                value={actorLabel(item.principal, locale)}
              />
              <MetadataRow
                label={t.decision}
                value={decisionLabels[localeName][item.decision]}
              />
              <MetadataRow label={t.ai} value={String(item.canGenerateAi)} />
              <MetadataRow label={t.source} value={item.sourceKey} />
              {item.decidedBy ? (
                <MetadataRow
                  label={t.decidedBy}
                  value={actorLabel(item.decidedBy, locale)}
                />
              ) : null}
              {item.comment ? (
                <View style={styles.item}>
                  <Text>{item.comment}</Text>
                </View>
              ) : null}
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{t.limitationTitle}</Text>
          {exportData.limitations.map(limitation => (
            <Text key={limitation.key} style={styles.limitation}>
              {limitation.key}: {limitation.description}
            </Text>
          ))}
        </View>
      </Page>
    </Document>
  )
}
