from pathlib import Path
import json,re,urllib.parse
O=Path('/workspace/tmp/sec-audit'); S=Path('/home/vscode/.codex/skills/security-audit')
# Exact source blocks, retained parent-side as assignment instructions.
def blocks(name):
 t=(S/name).read_text(); lines=t.splitlines(keepends=True); out={}; starts=[]
 for i,l in enumerate(lines):
  if l.startswith('**'):
   m=re.match(r'\*\*(.+?)\*\*',l)
   if m:starts.append((i,m[1]))
  elif l.startswith('## '):starts.append((i,l[3:].split(' (')[0].strip()))
 for n,(i,key) in enumerate(starts):
  end=starts[n+1][0] if n+1<len(starts) else len(lines)
  out[name+'#'+key]=''.join(lines[i:end]).rstrip()
 return out
B={}
for p in S.glob('*.md'):B.update(blocks(p.name))
A='ATTACK-CLASSES.md';W='WEB-PROTOCOL-AND-AUTH.md';D='DATA-ISOLATION-AND-LIFECYCLE.md';R='RESOURCE-EXHAUSTION-AND-AVAILABILITY.md';I='AI-AND-LLM.md';C='CLIENT-SIDE.md';P='PROTOCOLS-RPC-AND-MESSAGING.md';U='SUPPLY-CHAIN-AND-RELEASE.md';L='CLOUD-AND-DEPLOYMENT.md';F='DESKTOP-MOBILE-AND-LOCAL-IPC.md'
G=[]
def group(id,surface,boundary,subsystem,paths,ordinary,companions):
 G.append(dict(id=id,surface=surface,boundary=boundary,subsystem=subsystem,paths=paths,ordinary=ordinary,companions=companions))
group('auth','proxy.ts#HTTP entry','lib/auth/session.ts#authenticated identity','lib/auth',['proxy.ts','lib/auth','lib/http','app/api/auth','app/api/security','lib/security','next.config.ts'],['Access control','Cryptography and secrets','Obvious things'],{W:['Ordinary CSRF','Session fixation and invalidation','JWT verification and claim binding','OAuth/OIDC request and callback binding','Host and forwarded-header trust','Cache deception and private-response caching','Cookie scope and transport'],R:['Pre-authentication work imbalance']})
group('requirements','app/api/requirements#REST workflows','lib/requirements/assignment-authorization.ts#requirement authority','lib/requirements',['lib/requirements','lib/dal/requirements.ts','lib/dal/requirements-list-sql.mjs','app/api/requirements','app/api/requirement-transitions','app/api/improvement-suggestions','app/api/rfi-question-suggestions','app/api/requirement-areas','app/api/requirement-packages','app/api/norm-references','app/api/requirement-selection-questions'],['Access control','Injection','Business logic'],{D:['Policy and query disagreement','Import and restore authority expansion','Restore reintroduces invalid state','Stale authorization and derived copy use']})
group('specifications','app/api/requirements-specifications#REST workflows','lib/specifications/permissions.ts#specification authority','lib/specifications',['lib/specifications','lib/requirements/service-specifications.ts','lib/requirements/specification-mutations.ts','lib/dal/requirements-specifications.ts','lib/dal/deviations.ts','app/api/requirements-specifications','app/api/specification-local-requirements','app/api/deviations','app/api/specification-local-deviations'],['Access control','Business logic','Injection'],{D:['Missing tenant or owner enforcement','Policy and query disagreement','Import and restore authority expansion','Soft-delete and tombstone bypass']})
group('mcp','app/api/mcp/route.ts#MCP tools','lib/auth/mcp-token.ts#MCP principal','lib/mcp',['app/api/mcp/route.ts','lib/mcp','lib/auth/mcp-token.ts','lib/requirements/import-service.ts','lib/dal/requirement-import-validation-sessions.ts'],['Access control','Chained vulnerabilities and trust boundaries'],{I:['Sub-agent and MCP trust inheritance','MCP server and tool identity confusion','Tool-schema and dispatcher disagreement','Tool-argument injection into a downstream sink'],D:['Import and restore authority expansion'],R:['Quota-accounting scope and reset gaps']})
group('ai','app/api/ai#AI requests','lib/ai/run-trust-boundary.ts#provider and content authority','lib/ai',['lib/ai','app/api/ai','app/api/admin/ai-connections','app/api/admin/ai-settings','app/api/admin/ai-run-profiles','app/api/admin/ai-forensic-captures','lib/dal/ai-connection-admin.ts','scripts/ai-provider-secret-maintenance.mjs','scripts/ai-provider-secret-restore-cli.mjs'],['Resource and file handling','Cryptography and secrets','Business logic'],{I:['Indirect injection through retrieved or ingested content','Excessive agency and confused-deputy authority','Sensitive context extraction','Insecure output rendering'],R:['Detached work after cancellation','Quota-accounting scope and reset gaps']})
group('outputs','app/api/privacy#exports and reports','lib/privacy/route-helpers.ts#derived data authority','lib/privacy',['lib/privacy','lib/access-review','lib/archiving','lib/audit','lib/reports','lib/pdf','lib/generated-output','lib/transient-cleanup','app/api/privacy','app/api/admin/access-reviews','app/api/admin/archiving','app/api/admin/audit-events','app/api/requirements/export','app/api/requirements-specifications'],['Feature abuse and data leakage','Resource and file handling','Access control'],{D:['Export and backup scope expansion','Analytics, logs, traces, and diagnostics as alternate readers','Retention and queued-work overrun'],R:['File descriptor, handle, and temporary-resource leaks','Worker, pool, and priority starvation','Quota-accounting scope and reset gaps']})
group('browser','components#browser rendering','lib/norm-references/browser-link-uri.ts#untrusted content rendering','components',['components','app/[locale]','hooks','lib/norm-references/browser-link-uri.ts','lib/browser-download.ts','lib/export-csv.ts','next.config.ts'],['Injection','Feature abuse and data leakage'],{C:['DOM-based XSS','Prototype pollution and gadget chain','Browser-storage disclosure and stale authorization','Client-side navigation confusion','Credentialed CORS trust','Clickjacking']})
group('hsa','containers/hsa-person-lookup-adapter/src/strict-server.mjs#HSA ingress','lib/hsa/strict-certificate-validation.mjs#peer identity','containers/hsa-person-lookup-adapter',['lib/hsa','lib/requirements/responsibility-person-verification.ts','app/api/requirement-responsibility-people','containers/hsa-person-lookup-adapter','containers/hsa-directory-mock','containers/hsa-mtls-provisioner','containers/hsa-mtls-topology'],['Access control','Resource and file handling'],{W:['mTLS peer and application-identity confusion','Certificate lifecycle fallback'],P:['Message boundary and canonicalization disagreement','Envelope and payload identity mismatch','Callback and reply-correlation confusion'],R:['Unbounded buffering and cardinality']})
group('release','scripts/release/container-release.mjs#release inputs','scripts/release/publication.mjs#publication authority','scripts/release',['.github/workflows','scripts/release','scripts/containers/export-oci-archives.mjs','scripts/install-repository-npm.mjs','package-lock.json','package.json','containers/app/Dockerfile','containers/app/Dockerfile.dockerignore','.github/skills/security-audit'],['Resource and file handling','Obvious things','Chained vulnerabilities and trust boundaries'],{U:['Mutable and unbound build inputs','Untrusted code in a privileged workflow','Workflow command and expression confusion','Cache, artifact, and workspace trust mixing','Build-to-promotion substitution','Release authorization and signing-policy gaps','Build-context inclusion']})
group('operations','containers/production/bin#operator inputs','containers/production/bin/kravhantering-quadlet.sh#host authority','containers/production',['containers/production','scripts/azure-dev.ps1','scripts/azure-dev','scripts/containers','scripts/db-sqlserver-admin.mjs','lib/typeorm','typeorm','lib/transient-cleanup','containers/app/start-runtime.mjs','.devcontainer','.env.example','.env.production'],['Injection','Resource and file handling','Obvious things'],{L:['Unexpected service or management-plane reachability','Host or control-plane capability exposure','Security-control precedence drift','Secret exposure across workload boundaries','Credential renewal and outage fallback'],F:['Privileged helper as confused deputy','Local file ownership and TOCTOU']})
units=[]
for g in G:
 chosen=[A+'#'+x for x in g['ordinary']]+[f+'#'+x for f,arr in g['companions'].items() for x in arr]
 exclusions=[]
 for f in [A]+list(g['companions']):
  for ref,txt in B.items():
   if ref.startswith(f+'#') and txt.startswith('**') and ref not in chosen:
    exclusions.append({'block':ref,'reason':'Outside this assignment boundary; source-wide review is split by subsystem. Return an uncovered entry if this class is reachable here.'})
 for ref in chosen:
  file=ref.split('#')[0]; comps=[]
  if file!=A:comps=[file+'#Core discipline',ref,file+'#Universal moves',file+'#Validation rules']
  cr={'surface':g['surface'],'boundary':g['boundary'],'subsystem':g['subsystem'],'attack_class':ref}
  units.append({'coverage_id':'::'.join(urllib.parse.quote(v,safe='-._~') for v in cr.values()),'canonical_refs':cr,'surface':g['surface'],'boundary':g['boundary'],'subsystem':g['subsystem'],'attack_class':ref.split('#')[1],'starting_paths':g['paths'],'ordinary_attack_class_block':ref if file==A else None,'selected_companion_blocks':comps,'excluded_blocks':exclusions,'prior_status':'none','attempts':[],'wave':1,'status':'planned','agent_id':None,'reviewed_paths':[],'local_checks':[],'result_fingerprints':[],'unresolved':[],'assignment_group':g['id']})
units.sort(key=lambda u:u['coverage_id'])
(O/'coverage-ledger.json').write_text(json.dumps(units,indent=2)+'\n')
(O/'groups.json').write_text(json.dumps(G,indent=2)+'\n')
(O/'block-text.json').write_text(json.dumps(B,indent=2)+'\n')
m=json.loads((O/'run-metadata.json').read_text());m['selected_companion_files']=sorted({f for g in G for f in g['companions']});m['planning']={'seeded_units':len(units),'hunter_assignments':len(G),'mandatory_recon_assignments':4,'mandatory_critic_assignments_minimum':2,'validation_reserve':'Two independent assignments per candidate; no user budget limit.','budget_covers_plan':True};m['agents_spent']=4;m['platform_thread_limit']=4;m['independence_constraint']='Only three child threads are available; additional spawn requests returned agent thread limit reached. Reused assignments cannot satisfy fresh-thread critic/verifier requirements; disclose incomplete workflow if unavailable at finalization.';(O/'run-metadata.json').write_text(json.dumps(m,indent=2)+'\n')
print('Seeded',len(units),'units in',len(G),'assignments')
