import type {
  DataSubjectExportItem,
  DataSubjectExportRelatedObject,
  DataSubjectExportSource,
  DataSubjectExportV1,
  DataSubjectExportValue,
} from '@/lib/privacy/data-subject-export-types'
import { formatActorDisplayNameForLocale } from '@/lib/privacy/display-name'

type LocaleKey = 'en' | 'sv'

type SectionId =
  | 'accessReviews'
  | 'actionLog'
  | 'activeAssignments'
  | 'coAuthoring'
  | 'history'
  | 'identity'
  | 'other'

export interface DataSubjectExportPdfRow {
  label: string
  value: string
}

export interface DataSubjectExportPdfEntry {
  description: string
  rows: DataSubjectExportPdfRow[]
  title: string
}

export interface DataSubjectExportPdfSection {
  description: string
  entries: DataSubjectExportPdfEntry[]
  id: SectionId
  title: string
}

export interface DataSubjectExportPdfModel {
  introduction: string
  limitations: string[]
  limitationTitle: string
  metadataRows: DataSubjectExportPdfRow[]
  sections: DataSubjectExportPdfSection[]
  summaryRows: DataSubjectExportPdfRow[]
  summaryTitle: string
  title: string
}

interface SourceInfo {
  description: string
  section: SectionId
  title: string
}

interface SectionText {
  description: string
  title: string
}

interface BuildEntrySource {
  items: DataSubjectExportSource['items']
  key: DataSubjectExportSource['key']
  objectKey: DataSubjectExportSource['objectKey']
}

const NAME_FIELDS = new Set([
  'completed_by_display_name',
  'created_by',
  'created_by_display_name',
  'decided_by',
  'decided_by_display_name',
  'display_name',
  'familyName',
  'first_name',
  'givenName',
  'last_name',
  'lead_display_name',
  'name',
  'owner_display_name',
  'principal_display_name',
  'resolved_by',
  'responsible_display_name',
  'reviewer_display_name',
])

const HIDDEN_FIELDS = new Set(['scope_key', 'sub', 'target_id'])

const TEXT = {
  en: {
    actionLogDescription:
      'Events where the person is stored as the actor who performed an action in the application.',
    actionLogTitle: 'Action log',
    activeAssignmentsDescription:
      'Current responsibilities and assignments that still point to the person.',
    activeAssignmentsTitle: 'Active assignments',
    accessReviewItem: 'Access review row',
    accessReviewsDescription:
      'Access review records where the person appears as reviewer, creator, principal or decision maker.',
    accessReviewsTitle: 'Access reviews',
    accessReviewRun: 'Access review',
    aiAccess: 'AI access',
    availableInJson:
      'This detail is available in the machine-readable JSON export.',
    coAuthoringDescription:
      'Co-author assignments and app-managed AI permissions connected to the person.',
    coAuthoringTitle: 'Co-authoring and AI access',
    context: 'Context',
    generated: 'Generated',
    generatedBy: 'Generated by',
    hsaId: 'HSA-ID',
    identityDescription:
      'Identity, contact details and sign-in information connected to the person.',
    identityTitle: 'Identity and contact details',
    introduction:
      'This PDF summarizes the personal data the application found for the selected HSA-ID in plain language. The JSON file remains the machine-readable data portability format under the GDPR.',
    limitationTitle: 'Important limitations',
    no: 'No',
    noValue: 'Not available',
    objectFallback: 'System record',
    otherDescription: 'Other personal data found by the export collector.',
    otherTitle: 'Other data',
    pageTitle: 'Personal data export',
    rowUnknown: 'Information',
    sourceFallbackDescription:
      'The application stores this personal data in one of its structured records.',
    sourceFallbackTitle: 'Personal data in the application',
    subject: 'Person',
    summaryFields: 'Personal data fields',
    summaryLimitations: 'Limitations',
    summarySources: 'Areas with matches',
    summaryTitle: 'Summary',
    timestamp: 'Date',
    yes: 'Yes',
  },
  sv: {
    actionLogDescription:
      'Händelser där personen lagras som den aktör som utförde en åtgärd i applikationen.',
    actionLogTitle: 'Åtgärdslogg',
    activeAssignmentsDescription:
      'Aktuella ansvar och tilldelningar som fortfarande pekar ut personen.',
    activeAssignmentsTitle: 'Aktiva uppdrag',
    accessReviewItem: 'Rad i behörighetsöversyn',
    accessReviewsDescription:
      'Behörighetsöversyner där personen förekommer som granskare, skapare, behörig person eller beslutsfattare.',
    accessReviewsTitle: 'Behörighetsöversyner',
    accessReviewRun: 'Behörighetsöversyn',
    aiAccess: 'AI-behörighet',
    availableInJson: 'Uppgiften finns i den maskinläsbara JSON-exporten.',
    coAuthoringDescription:
      'Uppdrag som medförfattare och AI-behörigheter i appen som är kopplade till personen.',
    coAuthoringTitle: 'Medförfattare och AI-behörighet',
    context: 'Sammanhang',
    generated: 'Skapad',
    generatedBy: 'Skapad av',
    hsaId: 'HSA-ID',
    identityDescription:
      'Identitet, kontaktuppgifter och inloggningsuppgifter som är kopplade till personen.',
    identityTitle: 'Identitet och kontaktuppgifter',
    introduction:
      'Den här PDF-filen sammanfattar de personuppgifter som applikationen hittade för valt HSA-ID med tydligt språk. JSON-filen är fortsatt det maskinläsbara formatet för dataportabilitet enligt dataskyddsförordningen.',
    limitationTitle: 'Viktiga begränsningar',
    no: 'Nej',
    noValue: 'Saknas',
    objectFallback: 'Post i systemet',
    otherDescription: 'Andra personuppgifter som exporten hittade.',
    otherTitle: 'Övriga uppgifter',
    pageTitle: 'Export av personuppgifter',
    rowUnknown: 'Uppgift',
    sourceFallbackDescription:
      'Applikationen lagrar den här personuppgiften i en strukturerad post.',
    sourceFallbackTitle: 'Personuppgift i applikationen',
    subject: 'Person',
    summaryFields: 'Personuppgifter',
    summaryLimitations: 'Begränsningar',
    summarySources: 'Områden med träffar',
    summaryTitle: 'Sammanfattning',
    timestamp: 'Tidpunkt',
    yes: 'Ja',
  },
} as const

const SECTION_ORDER: SectionId[] = [
  'identity',
  'activeAssignments',
  'coAuthoring',
  'history',
  'accessReviews',
  'actionLog',
  'other',
]

const SOURCE_TEXT: Record<LocaleKey, Record<string, SourceInfo>> = {
  en: {
    'access_review_items.decided_by': {
      description:
        'A decision in an access review was registered by this person.',
      section: 'accessReviews',
      title: 'Decision in an access review',
    },
    'access_review_items.principal': {
      description:
        'An access review checked an assignment or permission for this person.',
      section: 'accessReviews',
      title: 'Reviewed permission',
    },
    'access_review_runs.completed_by': {
      description: 'This person completed an access review.',
      section: 'accessReviews',
      title: 'Completed access review',
    },
    'access_review_runs.created_by': {
      description: 'This person created an access review.',
      section: 'accessReviews',
      title: 'Created access review',
    },
    'access_review_runs.reviewer': {
      description: 'This person was assigned as reviewer for an access review.',
      section: 'accessReviews',
      title: 'Reviewer in access review',
    },
    'action_audit_events.actor': {
      description:
        'The application has stored that this person performed an action.',
      section: 'actionLog',
      title: 'Application action',
    },
    'auth.session': {
      description:
        'Current sign-in information is included only when a person exports their own data.',
      section: 'identity',
      title: 'Current sign-in session',
    },
    'deviations.created_by': {
      description: 'This person is stored as creator of a deviation.',
      section: 'history',
      title: 'Created deviation',
    },
    'deviations.decided_by': {
      description: 'This person is stored as decision maker for a deviation.',
      section: 'history',
      title: 'Decided deviation',
    },
    'improvement_suggestions.created_by': {
      description:
        'This person is stored as creator of an improvement suggestion.',
      section: 'history',
      title: 'Created improvement suggestion',
    },
    'improvement_suggestions.resolved_by': {
      description:
        'This person is stored as the person who resolved an improvement suggestion.',
      section: 'history',
      title: 'Resolved improvement suggestion',
    },
    'requirement_area_co_authors.created_by': {
      description:
        'This person is stored as the person who created a co-author assignment.',
      section: 'history',
      title: 'Created co-author assignment',
    },
    'requirement_area_co_authors.hsa_id': {
      description: 'The person is an active co-author for a requirement area.',
      section: 'coAuthoring',
      title: 'Requirement area co-author',
    },
    'requirement_package_co_authors.created_by': {
      description:
        'This person is stored as the person who created a package co-author assignment.',
      section: 'history',
      title: 'Created package co-author assignment',
    },
    'requirement_package_co_authors.hsa_id': {
      description:
        'The person is an active co-author for a requirements package.',
      section: 'coAuthoring',
      title: 'Requirements package co-author',
    },
    'requirement_areas.owner': {
      description: 'The person is assigned as owner for a requirement area.',
      section: 'activeAssignments',
      title: 'Requirement area owner',
    },
    'requirement_responsibility_people.identity': {
      description:
        'The person is stored once for active requirement responsibility assignments.',
      section: 'activeAssignments',
      title: 'Requirement responsibility person',
    },
    'requirement_packages.owner': {
      description:
        'The person is assigned as owner for a requirements package.',
      section: 'activeAssignments',
      title: 'Requirements package owner',
    },
    'requirement_versions.created_by': {
      description: 'This person is stored as creator of a requirement version.',
      section: 'history',
      title: 'Created by on requirement version',
    },
    'requirements_specifications.responsible': {
      description:
        'The person is assigned as responsible person for a requirements specification.',
      section: 'activeAssignments',
      title: 'Requirements specification lead',
    },
    'specification_co_authors.created_by': {
      description:
        'This person is stored as the person who created a co-author assignment.',
      section: 'history',
      title: 'Created co-author assignment',
    },
    'specification_co_authors.hsa_id': {
      description:
        'The person is an active co-author for a requirements specification.',
      section: 'coAuthoring',
      title: 'Requirements specification co-author',
    },
    'specification_local_requirement_deviations.created_by': {
      description:
        'This person is stored as creator of a local deviation in a requirements specification.',
      section: 'history',
      title: 'Created local deviation',
    },
    'specification_local_requirement_deviations.decided_by': {
      description:
        'This person is stored as decision maker for a local deviation in a requirements specification.',
      section: 'history',
      title: 'Decided local deviation',
    },
  },
  sv: {
    'access_review_items.decided_by': {
      description:
        'Ett beslut i en behörighetsöversyn har registrerats av personen.',
      section: 'accessReviews',
      title: 'Beslut i behörighetsöversyn',
    },
    'access_review_items.principal': {
      description:
        'En behörighetsöversyn har kontrollerat ett uppdrag eller en behörighet för personen.',
      section: 'accessReviews',
      title: 'Granskad behörighet',
    },
    'access_review_runs.completed_by': {
      description: 'Personen har slutfört en behörighetsöversyn.',
      section: 'accessReviews',
      title: 'Slutförd behörighetsöversyn',
    },
    'access_review_runs.created_by': {
      description: 'Personen har skapat en behörighetsöversyn.',
      section: 'accessReviews',
      title: 'Skapad behörighetsöversyn',
    },
    'access_review_runs.reviewer': {
      description:
        'Personen har varit utsedd granskare i en behörighetsöversyn.',
      section: 'accessReviews',
      title: 'Granskare i behörighetsöversyn',
    },
    'action_audit_events.actor': {
      description: 'Applikationen har sparat att personen utförde en åtgärd.',
      section: 'actionLog',
      title: 'Åtgärd i applikationen',
    },
    'auth.session': {
      description:
        'Aktuella inloggningsuppgifter ingår bara när en person exporterar sina egna uppgifter.',
      section: 'identity',
      title: 'Aktuell inloggningssession',
    },
    'deviations.created_by': {
      description: 'Personen står sparad som skapare av en avvikelse.',
      section: 'history',
      title: 'Skapad av på avvikelse',
    },
    'deviations.decided_by': {
      description: 'Personen står sparad som beslutsfattare för en avvikelse.',
      section: 'history',
      title: 'Beslutad av på avvikelse',
    },
    'improvement_suggestions.created_by': {
      description:
        'Personen står sparad som skapare av ett förbättringsförslag.',
      section: 'history',
      title: 'Skapad av på förbättringsförslag',
    },
    'improvement_suggestions.resolved_by': {
      description:
        'Personen står sparad som den som åtgärdade ett förbättringsförslag.',
      section: 'history',
      title: 'Åtgärdad av på förbättringsförslag',
    },
    'requirement_area_co_authors.created_by': {
      description:
        'Personen står sparad som den som skapade en tilldelning som medförfattare.',
      section: 'history',
      title: 'Skapad tilldelning som medförfattare',
    },
    'requirement_area_co_authors.hsa_id': {
      description: 'Personen är aktiv medförfattare i ett kravområde.',
      section: 'coAuthoring',
      title: 'Medförfattare i kravområde',
    },
    'requirement_package_co_authors.created_by': {
      description:
        'Personen står sparad som den som skapade en tilldelning som kravpaketsmedförfattare.',
      section: 'history',
      title: 'Skapad tilldelning som kravpaketsmedförfattare',
    },
    'requirement_package_co_authors.hsa_id': {
      description: 'Personen är aktiv medförfattare i ett kravpaket.',
      section: 'coAuthoring',
      title: 'Medförfattare i kravpaket',
    },
    'requirement_areas.owner': {
      description: 'Personen är utsedd ägare för ett kravområde.',
      section: 'activeAssignments',
      title: 'Ägare för kravområde',
    },
    'requirement_responsibility_people.identity': {
      description:
        'Personen lagras en gång för aktiva kravansvarstilldelningar.',
      section: 'activeAssignments',
      title: 'Kravansvarsperson',
    },
    'requirement_packages.owner': {
      description: 'Personen är utsedd ägare för ett kravpaket.',
      section: 'activeAssignments',
      title: 'Ägare för kravpaket',
    },
    'requirement_versions.created_by': {
      description: 'Personen står sparad som skapare av en kravversion.',
      section: 'history',
      title: 'Skapad av på kravversion',
    },
    'requirements_specifications.responsible': {
      description: 'Personen är ansvarig för ett kravunderlag.',
      section: 'activeAssignments',
      title: 'Ansvarig för kravunderlag',
    },
    'specification_co_authors.created_by': {
      description:
        'Personen står sparad som den som skapade en tilldelning som medförfattare.',
      section: 'history',
      title: 'Skapad tilldelning som medförfattare',
    },
    'specification_co_authors.hsa_id': {
      description: 'Personen är aktiv medförfattare i ett kravunderlag.',
      section: 'coAuthoring',
      title: 'Medförfattare i kravunderlag',
    },
    'specification_local_requirement_deviations.created_by': {
      description:
        'Personen står sparad som skapare av en lokal avvikelse i ett kravunderlag.',
      section: 'history',
      title: 'Skapad av på lokal avvikelse',
    },
    'specification_local_requirement_deviations.decided_by': {
      description:
        'Personen står sparad som beslutsfattare för en lokal avvikelse i ett kravunderlag.',
      section: 'history',
      title: 'Beslutad av på lokal avvikelse',
    },
  },
}

const FIELD_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    action: 'Action',
    actor_display_name: 'Name',
    actor_hsa_id: 'HSA-ID',
    can_generate_ai: 'AI access',
    can_responsible_generate_ai: 'AI access',
    completed_by_display_name: 'Name',
    completed_by_hsa_id: 'HSA-ID',
    created_by: 'Name',
    created_by_display_name: 'Name',
    created_by_hsa_id: 'HSA-ID',
    decided_by: 'Name',
    decided_by_display_name: 'Name',
    decided_by_hsa_id: 'HSA-ID',
    decision: 'Decision',
    display_name: 'Name',
    due_at: 'Due date',
    email: 'Email address',
    expiresAt: 'Session valid until',
    external_evidence_reference: 'External evidence',
    familyName: 'Family name',
    first_name: 'First name',
    given_name: 'Given name',
    givenName: 'Given name',
    hsa_id: 'HSA-ID',
    hsaId: 'HSA-ID',
    last_fetched_at: 'Last fetched',
    last_name: 'Last name',
    lead_display_name: 'Name',
    lead_hsa_id: 'HSA-ID',
    middle_name: 'Middle name',
    name: 'Name',
    owner_display_name: 'Name',
    owner_hsa_id: 'HSA-ID',
    period_end: 'Review period ends',
    period_start: 'Review period starts',
    permission_type: 'Permission',
    principal_display_name: 'Name',
    principal_hsa_id: 'HSA-ID',
    resolved_by: 'Name',
    resolved_by_hsa_id: 'HSA-ID',
    responsible_display_name: 'Name',
    responsible_hsa_id: 'HSA-ID',
    reviewer_display_name: 'Name',
    reviewer_hsa_id: 'HSA-ID',
    roles: 'Roles',
    scope_label: 'Scope',
    scope_type: 'Scope type',
    source_key: 'Permission source',
    status: 'Status',
    surname: 'Surname',
    target_kind: 'Affected object type',
    target_unique_id: 'Affected object',
  },
  sv: {
    action: 'Åtgärd',
    actor_display_name: 'Namn',
    actor_hsa_id: 'HSA-ID',
    can_generate_ai: 'AI-behörighet',
    can_responsible_generate_ai: 'AI-behörighet',
    completed_by_display_name: 'Namn',
    completed_by_hsa_id: 'HSA-ID',
    created_by: 'Namn',
    created_by_display_name: 'Namn',
    created_by_hsa_id: 'HSA-ID',
    decided_by: 'Namn',
    decided_by_display_name: 'Namn',
    decided_by_hsa_id: 'HSA-ID',
    decision: 'Beslut',
    display_name: 'Namn',
    due_at: 'Förfaller',
    email: 'E-postadress',
    expiresAt: 'Sessionen gäller till',
    external_evidence_reference: 'Extern evidens',
    familyName: 'Efternamn',
    first_name: 'Förnamn',
    given_name: 'Förnamn',
    givenName: 'Förnamn',
    hsa_id: 'HSA-ID',
    hsaId: 'HSA-ID',
    last_fetched_at: 'Senast hämtad',
    last_name: 'Efternamn',
    lead_display_name: 'Namn',
    lead_hsa_id: 'HSA-ID',
    middle_name: 'Mellannamn',
    name: 'Namn',
    owner_display_name: 'Namn',
    owner_hsa_id: 'HSA-ID',
    period_end: 'Granskningsperiod slutar',
    period_start: 'Granskningsperiod börjar',
    permission_type: 'Behörighet',
    principal_display_name: 'Namn',
    principal_hsa_id: 'HSA-ID',
    resolved_by: 'Namn',
    resolved_by_hsa_id: 'HSA-ID',
    responsible_display_name: 'Namn',
    responsible_hsa_id: 'HSA-ID',
    reviewer_display_name: 'Namn',
    reviewer_hsa_id: 'HSA-ID',
    roles: 'Roller',
    scope_label: 'Omfattning',
    scope_type: 'Typ av omfattning',
    source_key: 'Källa för behörighet',
    status: 'Status',
    surname: 'Efternamn',
    target_kind: 'Typ av berört objekt',
    target_unique_id: 'Berört objekt',
  },
}

const DECISION_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    allowed: 'Allowed',
    approved: 'Approved',
    changed: 'Changed',
    denied: 'Denied',
    not_applicable: 'Not applicable',
    pending: 'Pending',
    revoke_required: 'Revoke required',
  },
  sv: {
    allowed: 'Tillåten',
    approved: 'Godkänd',
    changed: 'Ändrad',
    denied: 'Nekad',
    not_applicable: 'Ej tillämplig',
    pending: 'Väntar',
    revoke_required: 'Återkalla',
  },
}

const STATUS_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    cancelled: 'Cancelled',
    completed: 'Completed',
    draft: 'Draft',
    in_review: 'In review',
  },
  sv: {
    cancelled: 'Avbruten',
    completed: 'Slutförd',
    draft: 'Utkast',
    in_review: 'Pågår',
  },
}

const PERMISSION_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    area_co_author: 'Requirement area co-author',
    area_owner: 'Requirement area owner',
    package_co_author: 'Requirements package co-author',
    package_owner: 'Requirements package owner',
    specification_co_author: 'Requirements specification co-author',
    specification_responsible: 'Requirements specification lead',
  },
  sv: {
    area_co_author: 'Medförfattare i kravområde',
    area_owner: 'Ägare för kravområde',
    package_co_author: 'Medförfattare i kravpaket',
    package_owner: 'Ägare för kravpaket',
    specification_co_author: 'Medförfattare i kravunderlag',
    specification_responsible: 'Ansvarig för kravunderlag',
  },
}

const SCOPE_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    requirement_area: 'Requirement area',
    requirements_specification: 'Requirements specification',
  },
  sv: {
    requirement_area: 'Kravområde',
    requirements_specification: 'Kravunderlag',
  },
}

const ROLE_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    Admin: 'Admin',
    PrivacyOfficer: 'Privacy officer',
    Reviewer: 'Reviewer',
  },
  sv: {
    Admin: 'Administratör',
    PrivacyOfficer: 'Dataskyddshandläggare',
    Reviewer: 'Granskare',
  },
}

const ACTION_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    'deviation.decision.recorded': 'Deviation decision recorded',
    'deviation.deleted': 'Deviation deleted',
    'privacy.erasure.execute': 'Privacy erasure executed',
    'requirement.archiving.approved': 'Requirement archiving approved',
    'requirement.archiving.cancelled': 'Requirement archiving cancelled',
    'requirement.archiving.initiated': 'Requirement archiving initiated',
    'requirement.create': 'Requirement created',
    'requirement.draft.deleted': 'Requirement draft deleted',
    'requirement.edit': 'Requirement edited',
    'requirement.reactivated': 'Requirement restored',
    'requirement.transition': 'Requirement status changed',
    'requirement.version.restored': 'Requirement version restored',
    'specification.requirements.added': 'Requirement added to specification',
    'specification.requirements.removed':
      'Requirement removed from specification',
    'specification_local_requirement.graduated':
      'Local requirement moved to the library',
    'suggestion.deleted': 'Improvement suggestion deleted',
    'suggestion.resolution.recorded':
      'Improvement suggestion decision recorded',
  },
  sv: {
    'deviation.decision.recorded': 'Beslut om avvikelse registrerades',
    'deviation.deleted': 'Avvikelse togs bort',
    'privacy.erasure.execute': 'Dataskyddsradering genomfördes',
    'requirement.archiving.approved': 'Arkivering av krav godkändes',
    'requirement.archiving.cancelled': 'Arkivering av krav avbröts',
    'requirement.archiving.initiated': 'Arkivering av krav påbörjades',
    'requirement.create': 'Krav skapades',
    'requirement.draft.deleted': 'Kravutkast togs bort',
    'requirement.edit': 'Krav ändrades',
    'requirement.reactivated': 'Krav återställdes',
    'requirement.transition': 'Kravstatus ändrades',
    'requirement.version.restored': 'Kravversion återställdes',
    'specification.requirements.added': 'Krav lades till i kravunderlag',
    'specification.requirements.removed': 'Krav togs bort från kravunderlag',
    'specification_local_requirement.graduated':
      'Lokalt krav flyttades till kravbiblioteket',
    'suggestion.deleted': 'Förbättringsförslag togs bort',
    'suggestion.resolution.recorded':
      'Beslut om förbättringsförslag registrerades',
  },
}

const TARGET_KIND_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    AccessReview: 'Access review',
    Deviation: 'Deviation',
    ImprovementSuggestion: 'Improvement suggestion',
    Requirement: 'Requirement',
    RequirementsSpecification: 'Requirements specification',
    SpecificationLocalRequirement: 'Local requirement',
  },
  sv: {
    AccessReview: 'Behörighetsöversyn',
    Deviation: 'Avvikelse',
    ImprovementSuggestion: 'Förbättringsförslag',
    Requirement: 'Krav',
    RequirementsSpecification: 'Kravunderlag',
    SpecificationLocalRequirement: 'Lokalt krav',
  },
}

const RELATED_OBJECT_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    access_review_item: 'Access review row',
    access_review_run: 'Access review',
    action_audit_event: 'Action log event',
    auth_session: 'Current sign-in session',
    deviation: 'Deviation',
    improvement_suggestion: 'Improvement suggestion',
    owner: 'Owner profile',
    requirement_area: 'Requirement area',
    requirement_package: 'Requirements package',
    requirement_version: 'Requirement version',
    requirements_specification: 'Requirements specification',
    specification_local_requirement_deviation: 'Local deviation',
  },
  sv: {
    access_review_item: 'Rad i behörighetsöversyn',
    access_review_run: 'Behörighetsöversyn',
    action_audit_event: 'Händelse i åtgärdsloggen',
    auth_session: 'Aktuell inloggningssession',
    deviation: 'Avvikelse',
    improvement_suggestion: 'Förbättringsförslag',
    owner: 'Ägarprofil',
    requirement_area: 'Kravområde',
    requirement_package: 'Kravpaket',
    requirement_version: 'Kravversion',
    requirements_specification: 'Kravunderlag',
    specification_local_requirement_deviation: 'Lokal avvikelse',
  },
}

const LIMITATION_LABELS: Record<LocaleKey, Record<string, string>> = {
  en: {
    direct_transfer_not_implemented:
      'Direct transfer to another controller is not available in this version. Use the JSON file when a machine-readable copy is needed.',
    free_text_not_scanned:
      'Free-text fields are not scanned because users are instructed not to enter personal data there.',
    security_audit_logs_external:
      'Platform security logs are handled in the operational log stream and are not included in this application export.',
    session_claims_self_only:
      'Current sign-in session details are included only when you export your own data.',
  },
  sv: {
    direct_transfer_not_implemented:
      'Direkt överföring till en annan personuppgiftsansvarig finns inte i den här versionen. Använd JSON-filen när en maskinläsbar kopia behövs.',
    free_text_not_scanned:
      'Fritextfält söks inte igenom eftersom användare instrueras att inte skriva personuppgifter där.',
    security_audit_logs_external:
      'Plattformens säkerhetsloggar hanteras i driftens loggström och ingår inte i den här exporten från applikationen.',
    session_claims_self_only:
      'Aktuella inloggningsuppgifter ingår bara när du exporterar dina egna uppgifter.',
  },
}

function localeKey(locale: string): LocaleKey {
  return locale === 'en' ? 'en' : 'sv'
}

function sectionText(locale: LocaleKey, id: SectionId): SectionText {
  const t = TEXT[locale]
  const textBySection = {
    accessReviews: {
      description: t.accessReviewsDescription,
      title: t.accessReviewsTitle,
    },
    actionLog: {
      description: t.actionLogDescription,
      title: t.actionLogTitle,
    },
    activeAssignments: {
      description: t.activeAssignmentsDescription,
      title: t.activeAssignmentsTitle,
    },
    coAuthoring: {
      description: t.coAuthoringDescription,
      title: t.coAuthoringTitle,
    },
    history: {
      description:
        locale === 'sv'
          ? 'Historiska spår där personen står sparad som skapare, beslutsfattare eller den som åtgärdade något.'
          : 'Historical traces where the person is stored as creator, decision maker or resolver.',
      title: locale === 'sv' ? 'Historiska spår' : 'Historical traces',
    },
    identity: {
      description: t.identityDescription,
      title: t.identityTitle,
    },
    other: {
      description: t.otherDescription,
      title: t.otherTitle,
    },
  } satisfies Record<SectionId, SectionText>

  return textBySection[id]
}

function sourceInfo(
  sourceKey: string,
  objectKey: string,
  locale: LocaleKey,
): SourceInfo {
  const known = SOURCE_TEXT[locale][sourceKey]
  if (known) return known
  if (objectKey === 'authSession') {
    return SOURCE_TEXT[locale]['auth.session']
  }
  return {
    description: TEXT[locale].sourceFallbackDescription,
    section: 'other',
    title: TEXT[locale].sourceFallbackTitle,
  }
}

function formatTimestamp(value: string, locale: LocaleKey): string {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleString(locale)
}

function formatEpochSeconds(value: number, locale: LocaleKey): string {
  const date = new Date(value * 1000)
  if (Number.isNaN(date.getTime())) return TEXT[locale].noValue
  return date.toLocaleString(locale)
}

function mappedValue(
  value: string,
  map: Record<LocaleKey, Record<string, string>>,
  locale: LocaleKey,
): string {
  return map[locale][value] ?? TEXT[locale].availableInJson
}

function formatFieldValue(
  fieldName: string,
  value: DataSubjectExportValue,
  locale: LocaleKey,
): string {
  const t = TEXT[locale]
  if (value == null) return t.noValue
  if (Array.isArray(value)) {
    return value
      .map(item =>
        fieldName === 'roles'
          ? (ROLE_LABELS[locale][item] ?? t.availableInJson)
          : item,
      )
      .join(', ')
  }
  if (typeof value === 'boolean') return value ? t.yes : t.no
  if (typeof value === 'number') {
    return fieldName === 'expiresAt'
      ? formatEpochSeconds(value, locale)
      : String(value)
  }
  if (typeof value !== 'string') return t.availableInJson

  const stringified = value.trim()
  if (!stringified) return t.noValue
  if (NAME_FIELDS.has(fieldName)) {
    return formatActorDisplayNameForLocale(stringified, locale) ?? stringified
  }
  if (
    fieldName === 'due_at' ||
    fieldName === 'period_end' ||
    fieldName === 'period_start'
  ) {
    return formatTimestamp(stringified, locale)
  }
  if (fieldName === 'action') {
    return mappedValue(stringified, ACTION_LABELS, locale)
  }
  if (fieldName === 'decision') {
    return mappedValue(stringified, DECISION_LABELS, locale)
  }
  if (fieldName === 'permission_type') {
    return mappedValue(stringified, PERMISSION_LABELS, locale)
  }
  if (fieldName === 'scope_type') {
    return mappedValue(stringified, SCOPE_LABELS, locale)
  }
  if (fieldName === 'source_key') {
    return sourceInfo(stringified, '', locale).title
  }
  if (fieldName === 'status') {
    return mappedValue(stringified, STATUS_LABELS, locale)
  }
  if (fieldName === 'target_kind') {
    return mappedValue(stringified, TARGET_KIND_LABELS, locale)
  }
  if (!FIELD_LABELS[locale][fieldName]) {
    return t.availableInJson
  }
  return stringified
}

function formatFieldRow(
  item: DataSubjectExportItem,
  locale: LocaleKey,
): DataSubjectExportPdfRow | null {
  if (HIDDEN_FIELDS.has(item.fieldName)) return null
  const label = FIELD_LABELS[locale][item.fieldName] ?? TEXT[locale].rowUnknown
  return {
    label,
    value: formatFieldValue(item.fieldName, item.value, locale),
  }
}

function shouldUseRelatedObjectLabel(
  relatedObject: DataSubjectExportRelatedObject,
): boolean {
  return (
    Boolean(relatedObject.label) &&
    relatedObject.type !== 'access_review_item' &&
    relatedObject.type !== 'access_review_run'
  )
}

export function formatDataSubjectRelatedObjectLabel(
  relatedObject: DataSubjectExportRelatedObject,
  locale: string,
): string {
  const key = localeKey(locale)
  const objectTypeLabel = RELATED_OBJECT_LABELS[key][relatedObject.type]
  if (shouldUseRelatedObjectLabel(relatedObject)) {
    if (
      objectTypeLabel &&
      relatedObject.type !== 'auth_session' &&
      relatedObject.type !== 'owner'
    ) {
      return `${objectTypeLabel}: ${relatedObject.label}`
    }
    return relatedObject.label ?? TEXT[key].objectFallback
  }
  return objectTypeLabel ?? TEXT[key].objectFallback
}

function groupKey(item: DataSubjectExportItem): string {
  if (!item.relatedObject) return 'source'
  return `${item.relatedObject.type}:${item.relatedObject.key}`
}

function buildEntry(
  source: BuildEntrySource,
  items: DataSubjectExportItem[],
  locale: LocaleKey,
): DataSubjectExportPdfEntry | null {
  const info = sourceInfo(source.key, source.objectKey, locale)
  const relatedObject = items.find(item => item.relatedObject)?.relatedObject
  const rows = items
    .map(item => formatFieldRow(item, locale))
    .filter((row): row is DataSubjectExportPdfRow => row !== null)
  const timestamp = items.find(item => item.timestamp)?.timestamp

  if (timestamp) {
    rows.push({
      label: TEXT[locale].timestamp,
      value: formatTimestamp(timestamp, locale),
    })
  }

  if (rows.length < 1) return null
  rows.unshift({
    label: TEXT[locale].context,
    value: info.title,
  })

  return {
    description: info.description,
    rows,
    title: relatedObject
      ? formatDataSubjectRelatedObjectLabel(relatedObject, locale)
      : info.title,
  }
}

function buildSections(
  exportData: DataSubjectExportV1,
  locale: LocaleKey,
): DataSubjectExportPdfSection[] {
  const sections = new Map<SectionId, DataSubjectExportPdfSection>()

  for (const id of SECTION_ORDER) {
    const text = sectionText(locale, id)
    sections.set(id, {
      description: text.description,
      entries: [],
      id,
      title: text.title,
    })
  }

  for (const source of exportData.sources) {
    const info = sourceInfo(source.key, source.objectKey, locale)
    const grouped = new Map<string, DataSubjectExportItem[]>()
    for (const item of source.items) {
      const key = groupKey(item)
      grouped.set(key, [...(grouped.get(key) ?? []), item])
    }

    for (const items of grouped.values()) {
      const entry = buildEntry(source, items, locale)
      if (entry) {
        sections.get(info.section)?.entries.push(entry)
      }
    }
  }

  return SECTION_ORDER.map(id => sections.get(id)).filter(
    (section): section is DataSubjectExportPdfSection =>
      section !== undefined && section.entries.length > 0,
  )
}

function actorLabel(
  actor: DataSubjectExportV1['generatedBy'],
  locale: LocaleKey,
): string {
  const displayName =
    formatActorDisplayNameForLocale(actor.displayName, locale) ??
    actor.displayName
  return `${displayName} (${actor.hsaId})`
}

export function buildDataSubjectExportPdfModel(
  exportData: DataSubjectExportV1,
  locale: string,
): DataSubjectExportPdfModel {
  const key = localeKey(locale)
  const t = TEXT[key]

  return {
    introduction: t.introduction,
    limitationTitle: t.limitationTitle,
    limitations: exportData.limitations.map(
      limitation => LIMITATION_LABELS[key][limitation.key] ?? t.availableInJson,
    ),
    metadataRows: [
      {
        label: t.generated,
        value: formatTimestamp(exportData.generatedAt, key),
      },
      { label: t.subject, value: exportData.subject.hsaId },
      { label: t.generatedBy, value: actorLabel(exportData.generatedBy, key) },
    ],
    sections: buildSections(exportData, key),
    summaryRows: [
      {
        label: t.summaryFields,
        value: String(exportData.summary.itemCount),
      },
      {
        label: t.summarySources,
        value: String(exportData.summary.sourceCount),
      },
      {
        label: t.summaryLimitations,
        value: String(exportData.summary.limitationCount),
      },
    ],
    summaryTitle: t.summaryTitle,
    title: t.pageTitle,
  }
}
