const UP_STATEMENTS = [
  `ALTER TABLE [requirements_specification_items] ADD
    [valid_from] datetime2 NOT NULL CONSTRAINT [df_requirements_specification_items_valid_from] DEFAULT SYSUTCDATETIME(),
    [valid_until] datetime2 NULL,
    [binding_created_by_hsa_id] nvarchar(64) NULL,
    [needs_reference_snapshot] nvarchar(MAX) NULL;`,
  `UPDATE [requirements_specification_items] SET [valid_from] = [created_at];`,
  `ALTER TABLE [specification_local_requirements] ADD
    [valid_from] datetime2 NOT NULL CONSTRAINT [df_specification_local_requirements_valid_from] DEFAULT SYSUTCDATETIME(),
    [valid_until] datetime2 NULL,
    [binding_created_by_hsa_id] nvarchar(64) NULL,
    [needs_reference_snapshot] nvarchar(MAX) NULL;`,
  `UPDATE [specification_local_requirements] SET [valid_from] = [created_at];`,
  `DROP INDEX [uq_requirements_specification_items_specification_requirement] ON [requirements_specification_items];`,
  `CREATE UNIQUE INDEX [uq_requirements_specification_items_specification_requirement] ON [requirements_specification_items] ([requirements_specification_id], [requirement_id]) WHERE [valid_until] IS NULL;`,
  `DROP INDEX [uq_specification_local_requirements_specification_id_sequence_number] ON [specification_local_requirements];`,
  `CREATE UNIQUE INDEX [uq_specification_local_requirements_specification_id_sequence_number] ON [specification_local_requirements] ([specification_id], [sequence_number]) WHERE [valid_until] IS NULL;`,
  `DROP INDEX [uq_specification_local_requirements_specification_id_unique_id] ON [specification_local_requirements];`,
  `CREATE UNIQUE INDEX [uq_specification_local_requirements_specification_id_unique_id] ON [specification_local_requirements] ([specification_id], [unique_id]) WHERE [valid_until] IS NULL;`,
  `CREATE VIEW [current_requirement_applications] AS SELECT * FROM [requirements_specification_items]
    WHERE [valid_from] <= SYSUTCDATETIME() AND ([valid_until] IS NULL OR [valid_until] > SYSUTCDATETIME());`,
  `CREATE VIEW [current_specification_local_requirements] AS SELECT * FROM [specification_local_requirements]
    WHERE [valid_from] <= SYSUTCDATETIME() AND ([valid_until] IS NULL OR [valid_until] > SYSUTCDATETIME());`,
  `ALTER TABLE [specification_local_requirements] ADD [source_requirement_version_id] int NULL;`,
  `ALTER TABLE [specification_local_requirements] ADD CONSTRAINT [fk_specification_local_requirements_source_requirement_version_id] FOREIGN KEY ([source_requirement_version_id]) REFERENCES [requirement_versions] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `CREATE TABLE [specification_agreements] (
    [id] int IDENTITY(1,1) NOT NULL CONSTRAINT [pk_specification_agreements] PRIMARY KEY,
    [specification_id] int NOT NULL,
    [agreement_reference] nvarchar(450) NOT NULL,
    [effective_date] date NOT NULL,
    [description] nvarchar(MAX) NULL,
    [created_at] datetime2 NOT NULL,
    [created_by_hsa_id] nvarchar(64) NULL,
    [created_by_display_name] nvarchar(512) NULL,
    [confirmed_at] datetime2 NULL,
    [confirmed_by_hsa_id] nvarchar(64) NULL,
    [confirmed_by_display_name] nvarchar(512) NULL,
    [effective_at] datetime2 NULL,
    [activated_at] datetime2 NULL,
    [replaced_at] datetime2 NULL,
    [cancelled_at] datetime2 NULL,
    [cancelled_by_hsa_id] nvarchar(64) NULL,
    [cancelled_by_display_name] nvarchar(512) NULL,
    [cancellation_reason] nvarchar(MAX) NULL,
    [ended_at] datetime2 NULL,
    [ended_by_hsa_id] nvarchar(64) NULL,
    [ended_by_display_name] nvarchar(512) NULL,
    [end_date] date NULL,
    [end_reason] nvarchar(MAX) NULL,
    [is_pending] bit NOT NULL,
    [is_current] bit NOT NULL,
    [previous_agreement_id] int NULL
  );`,
  `CREATE UNIQUE INDEX [uq_specification_agreements_specification_reference] ON [specification_agreements] ([specification_id], [agreement_reference]);`,
  `CREATE UNIQUE INDEX [uq_specification_agreements_specification_date] ON [specification_agreements] ([specification_id], [effective_date]) WHERE [cancelled_at] IS NULL;`,
  `CREATE UNIQUE INDEX [uq_specification_agreements_pending] ON [specification_agreements] ([specification_id]) WHERE [is_pending] = 1;`,
  `CREATE UNIQUE INDEX [uq_specification_agreements_current] ON [specification_agreements] ([specification_id]) WHERE [is_current] = 1;`,
  `CREATE TABLE [specification_agreement_corrections] (
    [id] int IDENTITY(1,1) NOT NULL CONSTRAINT [pk_specification_agreement_corrections] PRIMARY KEY,
    [agreement_id] int NOT NULL,
    [old_agreement_reference] nvarchar(450) NOT NULL,
    [new_agreement_reference] nvarchar(450) NOT NULL,
    [old_effective_date] date NOT NULL,
    [new_effective_date] date NOT NULL,
    [old_description] nvarchar(MAX) NULL,
    [new_description] nvarchar(MAX) NULL,
    [corrected_at] datetime2 NOT NULL,
    [corrected_by_hsa_id] nvarchar(64) NULL,
    [corrected_by_display_name] nvarchar(512) NULL
  );`,
  `CREATE INDEX [idx_specification_agreement_corrections_agreement_id] ON [specification_agreement_corrections] ([agreement_id]);`,
  `CREATE TABLE [specification_agreement_items] (
    [id] int IDENTITY(1,1) NOT NULL CONSTRAINT [pk_specification_agreement_items] PRIMARY KEY,
    [specification_agreement_id] int NOT NULL,
    [specification_item_id] int NULL,
    [specification_local_requirement_id] int NULL,
    [previous_item_id] int NULL,
    [changed_in_agreement_id] int NULL,
    [change_kind] varchar(10) NULL CONSTRAINT [chk_specification_agreement_items_change_kind] CHECK ([change_kind] IN ('added', 'changed', 'removed')),
    [is_removed] bit NOT NULL CONSTRAINT [df_specification_agreement_items_is_removed] DEFAULT 0,
    [deviation_state_json] nvarchar(MAX) NULL,
    [has_followup_snapshot] bit NOT NULL CONSTRAINT [df_specification_agreement_items_has_followup_snapshot] DEFAULT 0,
    [specification_item_status_id] int NULL,
    [note] nvarchar(MAX) NULL,
    [needs_reference] nvarchar(MAX) NULL,
    [status_updated_at] datetime2 NULL,
    CONSTRAINT [chk_specification_agreement_items_binding] CHECK (([specification_item_id] IS NOT NULL AND [specification_local_requirement_id] IS NULL) OR ([specification_item_id] IS NULL AND [specification_local_requirement_id] IS NOT NULL))
  );`,
  `CREATE UNIQUE INDEX [uq_specification_agreement_items_library] ON [specification_agreement_items] ([specification_agreement_id], [specification_item_id]) WHERE [specification_item_id] IS NOT NULL;`,
  `CREATE UNIQUE INDEX [uq_specification_agreement_items_local] ON [specification_agreement_items] ([specification_agreement_id], [specification_local_requirement_id]) WHERE [specification_local_requirement_id] IS NOT NULL;`,
  `ALTER TABLE [requirements_specification_items] ADD [owning_agreement_id] int NULL;`,
  `ALTER TABLE [requirements_specification_items] ADD CONSTRAINT [fk_requirements_specification_items_owning_agreement_id] FOREIGN KEY ([owning_agreement_id]) REFERENCES [specification_agreements] ([id]) ON DELETE SET NULL ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_local_requirements] ADD [owning_agreement_id] int NULL;`,
  `ALTER TABLE [specification_local_requirements] ADD CONSTRAINT [fk_specification_local_requirements_owning_agreement_id] FOREIGN KEY ([owning_agreement_id]) REFERENCES [specification_agreements] ([id]) ON DELETE SET NULL ON UPDATE NO ACTION;`,
  `ALTER TABLE [requirements_specification_items] ADD [origin_agreement_item_id] int NULL;`,
  `ALTER TABLE [requirements_specification_items] ADD CONSTRAINT [fk_requirements_specification_items_origin_agreement_item_id] FOREIGN KEY ([origin_agreement_item_id]) REFERENCES [specification_agreement_items] ([id]) ON DELETE SET NULL ON UPDATE NO ACTION;`,
  `CREATE INDEX [idx_requirements_specification_items_origin_agreement_item_id] ON [requirements_specification_items] ([origin_agreement_item_id]);`,
  `ALTER TABLE [specification_local_requirements] ADD [origin_agreement_item_id] int NULL;`,
  `ALTER TABLE [specification_local_requirements] ADD CONSTRAINT [fk_specification_local_requirements_origin_agreement_item_id] FOREIGN KEY ([origin_agreement_item_id]) REFERENCES [specification_agreement_items] ([id]) ON DELETE SET NULL ON UPDATE NO ACTION;`,
  `CREATE INDEX [idx_specification_local_requirements_origin_agreement_item_id] ON [specification_local_requirements] ([origin_agreement_item_id]);`,
  `EXEC sp_refreshview N'current_requirement_applications';`,
  `EXEC sp_refreshview N'current_specification_local_requirements';`,
  `CREATE TABLE [specification_deviation_endings] (
    [id] int IDENTITY(1,1) NOT NULL CONSTRAINT [pk_specification_deviation_endings] PRIMARY KEY,
    [specification_id] int NOT NULL,
    [agreement_id] int NULL,
    [agreement_reference] nvarchar(450) NULL,
    [agreement_item_id] int NULL,
    [deviation_id] int NULL,
    [local_deviation_id] int NULL,
    [planned_effective_date] date NOT NULL,
    [recorded_at] datetime2 NOT NULL,
    [recorded_by_hsa_id] nvarchar(64) NULL,
    [cancelled_at] datetime2 NULL,
    [cancelled_by_hsa_id] nvarchar(64) NULL,
    [ended_at] datetime2 NULL,
    CONSTRAINT [chk_specification_deviation_endings_case] CHECK (([deviation_id] IS NOT NULL AND [local_deviation_id] IS NULL) OR ([deviation_id] IS NULL AND [local_deviation_id] IS NOT NULL))
  );`,
  `CREATE INDEX [idx_specification_deviation_endings_agreement_id] ON [specification_deviation_endings] ([agreement_id]);`,
  `ALTER TABLE [specification_agreements] ADD CONSTRAINT [fk_specification_agreements_specification_id] FOREIGN KEY ([specification_id]) REFERENCES [requirements_specifications] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_agreements] ADD CONSTRAINT [fk_specification_agreements_previous_agreement_id] FOREIGN KEY ([previous_agreement_id]) REFERENCES [specification_agreements] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_agreement_corrections] ADD CONSTRAINT [fk_specification_agreement_corrections_agreement_id] FOREIGN KEY ([agreement_id]) REFERENCES [specification_agreements] ([id]) ON DELETE CASCADE ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_agreement_items] ADD CONSTRAINT [fk_specification_agreement_items_specification_agreement_id] FOREIGN KEY ([specification_agreement_id]) REFERENCES [specification_agreements] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_agreement_items] ADD CONSTRAINT [fk_specification_agreement_items_specification_item_id] FOREIGN KEY ([specification_item_id]) REFERENCES [requirements_specification_items] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_agreement_items] ADD CONSTRAINT [fk_specification_agreement_items_specification_local_requirement_id] FOREIGN KEY ([specification_local_requirement_id]) REFERENCES [specification_local_requirements] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_agreement_items] ADD CONSTRAINT [fk_specification_agreement_items_previous_item_id] FOREIGN KEY ([previous_item_id]) REFERENCES [specification_agreement_items] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_agreement_items] ADD CONSTRAINT [fk_specification_agreement_items_changed_in_agreement_id] FOREIGN KEY ([changed_in_agreement_id]) REFERENCES [specification_agreements] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_agreement_items] ADD CONSTRAINT [fk_specification_agreement_items_specification_item_status_id] FOREIGN KEY ([specification_item_status_id]) REFERENCES [specification_item_statuses] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_deviation_endings] ADD CONSTRAINT [fk_specification_deviation_endings_specification_id] FOREIGN KEY ([specification_id]) REFERENCES [requirements_specifications] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_deviation_endings] ADD CONSTRAINT [fk_specification_deviation_endings_agreement_id] FOREIGN KEY ([agreement_id]) REFERENCES [specification_agreements] ([id]) ON DELETE SET NULL ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_deviation_endings] ADD CONSTRAINT [fk_specification_deviation_endings_agreement_item_id] FOREIGN KEY ([agreement_item_id]) REFERENCES [specification_agreement_items] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_deviation_endings] ADD CONSTRAINT [fk_specification_deviation_endings_deviation_id] FOREIGN KEY ([deviation_id]) REFERENCES [deviations] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
  `ALTER TABLE [specification_deviation_endings] ADD CONSTRAINT [fk_specification_deviation_endings_local_deviation_id] FOREIGN KEY ([local_deviation_id]) REFERENCES [specification_local_requirement_deviations] ([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;`,
]

export class SpecificationAgreements1789257600000 {
  name = 'SpecificationAgreements1789257600000'

  async up(queryRunner) {
    for (const statement of UP_STATEMENTS) await queryRunner.query(statement)
  }

  async down(queryRunner) {
    await queryRunner.query(
      `THROW 51000, 'Agreement history cannot be discarded by rollback. Restore a backup instead.', 1;`,
    )
  }
}
