// Dogfood seed: realistic Krav describing the Kravhantering application itself
// plus a "Kravhantering" Kravunderlag (uniqueId KH) that contains them all and a
// smaller "Kravhantering PoC införande" specification (uniqueId KH-POC).
//
// Strategy:
// - All new IDs use offsets well above the existing seed's max IDs to avoid
//   any collision (areas/norms/packages/owners/specifications: 1001+; krav,
//   versions, items: 10001+).
// - Krav are described as compact tuples in DOGFOOD_KRAV and expanded into
//   `requirements`, `requirement_versions`, and junction-table rows.
// - All Krav are version 1, status Publicerad (3), with a non-null
//   published_at. Single language (Swedish) for prose fields.
// - Anchors: every Krav corresponds to an actually shipping behaviour or file
//   in this repo (verified before being included).

const SEED_TS = '2026-04-22 09:00:00'

const ID = {
  // Reused lookups (defined by the base seed)
  cat: { verksamhet: 1, it: 2, leverantor: 3 },
  type: { funk: 1, ickefunk: 2 },
  risk: { lag: 1, medel: 2, hog: 3 },
  status: { utkast: 1, granskning: 2, publicerad: 3, arkiverad: 4 },
  itemStatus: {
    inkluderad: 1,
    pagaende: 2,
    implementerad: 3,
    verifierad: 4,
    avviken: 5,
    ejTillampbar: 6,
  },
  specLifecycle: {
    upphandling: 1,
    inforande: 2,
    utveckling: 3,
    forvaltning: 4,
  },
  specRespArea: {
    forvaltningsobjekt: 1,
    projekt: 2,
    uppdrag: 3,
    leveransomrade: 4,
    tjansteomrade: 5,
  },
  specImpl: { upphandling: 1, utveckling: 2 },
  // Existing requirement areas (id -> prefix). Sequence offsets are read from
  // SEED_DATA.requirement_areas when the dogfood rows are appended.
  area: {
    INT: 1,
    SAK: 2,
    PRE: 3,
    ANV: 4,
    LAG: 5,
    BEH: 6,
    IDN: 7,
    LOG: 8,
    DRF: 9,
    DAT: 10,
    // New areas added by this dogfood seed
    TIL: 1001,
    KVA: 1002,
    SPR: 1003,
    RAP: 1004,
    UTV: 1005,
    ARK: 1006,
  },
  // Existing norm refs (1-6). New ones below.
  norm: {
    sfs2018_218: 1,
    iso27001: 2,
    msbfs2020_6: 3,
    rfc6749: 4,
    iso25010: 5,
    nis2: 6,
    wcag22: 1001,
    en301549: 1002,
    oidcCore: 1003,
    asvs: 1004,
    gdpr: 1005,
    rfc9700: 1006,
  },
  // Existing requirement packages (1-9) plus new ones (1001+)
  pkg: {
    mobilAnvandning: 1,
    datamigrering: 2,
    integrationer: 3,
    arendehantering: 4,
    anvandarvanlighetBas: 5,
    molndrift: 6,
    grundSystem: 1001,
    infosak: 1002,
    behorighet: 1003,
    apiUtbyte: 1004,
    anvandbarhet: 1005,
    tillganglighet: 1006,
    sparbarhet: 1007,
    driftTillg: 1008,
    testKvalitet: 1009,
    versionshantering: 1010,
    sso: 1011,
    gdprPerson: 1012,
  },
  // Existing owners 1-3, new dogfood owners 1001+
  owner: {
    sara: 1001,
    karl: 1002,
    linnea: 1003,
    oscar: 1004,
    emma: 1005,
  },
  // Quality characteristics from base seed (selected ones we use here)
  qc: {
    funkLamplighet: 1,
    funkKorrekthet: 3,
    funkAndamalsenlighet: 4,
    tidsbeteende: 6,
    kapacitet: 8,
    interoperabilitet: 11,
    igenkannlighet: 13,
    inlarningsbarhet: 14,
    anvandbarhet: 15,
    skyddAnvFel: 16,
    inkludering: 18,
    hjalpmedelsanpassning: 19,
    sjalvbeskrivning: 20,
    tillganglighet: 23,
    aterstallningsbarhet: 25,
    konfidentialitet: 27,
    integritet: 28,
    oavvislighet: 29,
    ansvarsskyldighet: 30,
    akthet: 31,
    motstandskraft: 32,
    modularitet: 34,
    analyserbarhet: 36,
    andringsbarhet: 37,
    testbarhet: 38,
    anpassningsbarhet: 40,
    installerbarhet: 42,
  },
}

// Dogfood specification IDs (chosen high to avoid clashing with future seed growth)
const SPEC_KH = 1001
const SPEC_KH_POC = 1002

// Starting IDs for generated rows
const REQUIREMENT_ID_BASE = 10000
const VERSION_ID_BASE = 10000
const SPECIFICATION_ITEM_ID_BASE = 10000
const SPECIFICATION_LOCAL_ID_BASE = 1000
const NEEDS_REF_ID_BASE = 1000

const AREA_PREFIX_BY_ID = {
  [ID.area.INT]: 'INT',
  [ID.area.SAK]: 'SÄK',
  [ID.area.PRE]: 'PRE',
  [ID.area.ANV]: 'ANV',
  [ID.area.LAG]: 'LAG',
  [ID.area.BEH]: 'BEH',
  [ID.area.IDN]: 'IDN',
  [ID.area.LOG]: 'LOG',
  [ID.area.DRF]: 'DRF',
  [ID.area.DAT]: 'DAT',
  [ID.area.TIL]: 'TIL',
  [ID.area.KVA]: 'KVA',
  [ID.area.SPR]: 'SPR',
  [ID.area.RAP]: 'RAP',
  [ID.area.UTV]: 'UTV',
  [ID.area.ARK]: 'ARK',
}

// New owners (fake persons assigned to new areas, packages and needs refs)
const DOGFOOD_OWNERS = [
  [ID.owner.sara, 'Sara', 'Holm', 'sara.holm@example.com'],
  [ID.owner.karl, 'Karl', 'Persson', 'karl.persson@example.com'],
  [ID.owner.linnea, 'Linnéa', 'Bergström', 'linnea.bergstrom@example.com'],
  [ID.owner.oscar, 'Oscar', 'Nilsson', 'oscar.nilsson@example.com'],
  [ID.owner.emma, 'Emma', 'Lindqvist', 'emma.lindqvist@example.com'],
]

// New requirement areas. Sequence column is fixed up at the end based on
// how many Krav we end up authoring in each area.
const DOGFOOD_AREAS = [
  [
    ID.area.TIL,
    'TIL',
    'Tillgänglighet',
    'Krav för digital tillgänglighet enligt WCAG och EN 301 549',
    ID.owner.linnea,
  ],
  [
    ID.area.KVA,
    'KVA',
    'Kvalitetssäkring',
    'Krav på testning, statisk analys och kvalitetsportar',
    ID.owner.emma,
  ],
  [
    ID.area.SPR,
    'SPR',
    'Språkstöd',
    'Krav på flerspråkighet och översättningar',
    ID.owner.linnea,
  ],
  [
    ID.area.RAP,
    'RAP',
    'Rapportering',
    'Krav på rapportgenerering, export och utskrift',
    ID.owner.sara,
  ],
  [
    ID.area.UTV,
    'UTV',
    'Utvecklingsmiljö',
    'Krav på utvecklingsverktyg, skills och instruktioner för agenter',
    ID.owner.oscar,
  ],
  [
    ID.area.ARK,
    'ARK',
    'Arkitektur',
    'Krav på arkitekturella val, lager och teknikval',
    ID.owner.sara,
  ],
]

// New norm references
const DOGFOOD_NORMS = [
  [
    ID.norm.wcag22,
    'WCAG 2.2',
    'Web Content Accessibility Guidelines 2.2',
    'Standard',
    'WCAG 2.2',
    '2.2',
    'W3C',
    'https://www.w3.org/TR/WCAG22/',
  ],
  [
    ID.norm.en301549,
    'EN 301 549 v3.2.1',
    'Tillgänglighetskrav på IKT-produkter och IKT-tjänster',
    'Standard',
    'EN 301 549 v3.2.1',
    '3.2.1',
    'ETSI',
    'https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf',
  ],
  [
    ID.norm.oidcCore,
    'OpenID Connect Core 1.0',
    'OpenID Connect Core 1.0 incorporating errata set 2',
    'Standard',
    'OpenID Connect Core 1.0',
    '1.0',
    'OpenID Foundation',
    'https://openid.net/specs/openid-connect-core-1_0.html',
  ],
  [
    ID.norm.asvs,
    'OWASP ASVS 4.0.3',
    'Application Security Verification Standard',
    'Standard',
    'OWASP ASVS 4.0.3',
    '4.0.3',
    'OWASP',
    'https://owasp.org/www-project-application-security-verification-standard/',
  ],
  [
    ID.norm.gdpr,
    'EU 2016/679',
    'Allmänna dataskyddsförordningen (GDPR)',
    'Förordning',
    'EU 2016/679',
    null,
    'Europeiska unionens råd och Europaparlamentet',
    'https://eur-lex.europa.eu/eli/reg/2016/679',
  ],
  [
    ID.norm.rfc9700,
    'RFC 9700',
    'Best Current Practice for OAuth 2.0 Security',
    'Standard',
    'RFC 9700',
    null,
    'IETF',
    'https://datatracker.ietf.org/doc/html/rfc9700',
  ],
]

// New requirement packages (bilingual sv/en)
const DOGFOOD_REQUIREMENT_PACKAGES = [
  [
    ID.pkg.grundSystem,
    'Grundläggande systemstöd',
    'Core system support',
    'Krav för de viktigaste funktionerna som systemet måste stödja.',
    'Requirements for the essential functions the system must support.',
    ID.owner.sara,
  ],
  [
    ID.pkg.infosak,
    'Informationssäkerhet',
    'Information security',
    'Krav som skyddar information mot obehörig åtkomst, förlust eller manipulation.',
    'Requirements that protect information from unauthorized access, loss, or manipulation.',
    ID.owner.karl,
  ],
  [
    ID.pkg.behorighet,
    'Behörighetsstyrning',
    'Access control',
    'Krav för att styra vem som får se, ändra eller administrera information.',
    'Requirements for controlling who can view, change, or administer information.',
    ID.owner.karl,
  ],
  [
    ID.pkg.apiUtbyte,
    'API och informationsutbyte',
    'API and information exchange',
    'Krav för tekniska gränssnitt, dataflöden och maskin-till-maskin-kommunikation.',
    'Requirements for technical interfaces, data flows, and machine-to-machine communication.',
    ID.owner.sara,
  ],
  [
    ID.pkg.anvandbarhet,
    'Användarvänlighet',
    'Usability',
    'Krav för att systemet ska vara enkelt, effektivt och tydligt att använda.',
    'Requirements for making the system easy, efficient, and clear to use.',
    ID.owner.linnea,
  ],
  [
    ID.pkg.tillganglighet,
    'Tillgänglighet',
    'Accessibility',
    'Krav för att systemet ska kunna användas av personer med olika behov och förutsättningar.',
    'Requirements for making the system usable by people with different needs and abilities.',
    ID.owner.linnea,
  ],
  [
    ID.pkg.sparbarhet,
    'Spårbarhet och loggning',
    'Traceability and logging',
    'Krav för att kunna se vem som gjort vad, när och i vilket sammanhang.',
    'Requirements for seeing who did what, when, and in what context.',
    ID.owner.oscar,
  ],
  [
    ID.pkg.driftTillg,
    'Drift och tillgänglighet',
    'Operations and availability',
    'Krav för driftsmiljö, upptid, övervakning och teknisk stabilitet.',
    'Requirements for hosting, uptime, monitoring, and technical stability.',
    ID.owner.oscar,
  ],
  [
    ID.pkg.testKvalitet,
    'Test och kvalitetssäkring',
    'Testing and quality assurance',
    'Krav för testning, verifiering, acceptans och kvalitet i leveransen.',
    'Requirements for testing, verification, acceptance, and delivery quality.',
    ID.owner.emma,
  ],
  [
    ID.pkg.versionshantering,
    'Versionshantering',
    'Version control',
    'Krav för att hantera olika versioner av dokument, data, konfigurationer eller funktioner.',
    'Requirements for managing different versions of documents, data, configurations, or features.',
    ID.owner.sara,
  ],
  [
    ID.pkg.sso,
    'Single Sign-On',
    'Single Sign-On',
    'Krav för att användare ska kunna logga in via organisationens gemensamma inloggning.',
    'Requirements for users to log in through the organization’s shared identity solution.',
    ID.owner.karl,
  ],
  [
    ID.pkg.gdprPerson,
    'GDPR och personuppgifter',
    'GDPR and personal data',
    'Krav för hantering av personuppgifter enligt dataskyddsregler.',
    'Requirements for handling personal data according to data protection rules.',
    ID.owner.karl,
  ],
]

// Krav inventory: each row is
// { area, desc, ac, vm, cat, type, qc, risk, test, pkg: [], norm:[], item }
// The order here also defines the order of items in the KH specification.
const DOGFOOD_KRAV = [
  // ====== ARK – Arkitektur (4) ======
  {
    area: ID.area.ARK,
    desc: 'Applikationen ska bygga på Next.js App Router med React Server Components för all routing och rendering.',
    ac: 'All routing under app/ använder App Router-konventionen; inga sidor lever under pages/. Server Components är standard och Client Components markeras explicit med "use client".',
    vm: 'Manuell granskning av app/-trädet i kombination med statisk analys (lint) av "use client"-direktivet samt build-verifiering via npm run build.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.modularitet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.grundSystem],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.ARK,
    desc: 'Skrivvägar mot databasen ska gå genom DAL-lagret i lib/dal/ och får inte anropas direkt från API-routes eller komponenter.',
    ac: 'Alla skrivoperationer (INSERT/UPDATE/DELETE eller TypeORM-motsvarigheter) ligger i lib/dal/*.ts. API-routes anropar antingen DAL eller lib/requirements/service.ts som i sin tur anropar DAL.',
    vm: 'Kodgranskning samt grep efter direkta repository-skrivanrop utanför lib/dal/. Enhetstester verifierar att service-lagret delegerar till DAL.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.modularitet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.grundSystem],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.ARK,
    desc: 'Lagringsstacken ska vara Microsoft SQL Server tillgänglig via TypeORM som enda persisterings­teknik.',
    ac: 'Inga andra databas-drivare eller ORM:er förekommer i package.json. Migrationer och entiteter ligger i typeorm/ respektive lib/typeorm/entities/.',
    vm: 'Granskning av package.json mot tillåtna beroenden samt körning av migrationer mot lokal SQL Server-instans via docker-compose.sqlserver.yml.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.interoperabilitet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.grundSystem, ID.pkg.driftTillg],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.ARK,
    desc: 'Middleware ska skydda alla routes utom publika auth- och hälso-endpoints och omdirigera oautentiserade anrop till inloggning.',
    ac: 'middleware.ts matchar rätt undantagsmönster; oautentiserade anrop mot skyddade routes returnerar 302 mot /api/auth/login. Hälso- och auth-endpoints förblir åtkomliga utan session.',
    vm: 'Enhets- och integrationstester av middleware-matchning samt manuell verifiering med scripts/dev-curl.sh utan giltig sessionscookie.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.akthet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.infosak, ID.pkg.behorighet],
    norm: [ID.norm.asvs],
    item: ID.itemStatus.verifierad,
  },

  // ====== INT – Integration (5) ======
  {
    area: ID.area.INT,
    desc: 'Systemet ska exponera en MCP HTTP-endpoint på POST /api/mcp som returnerar JSON-RPC 2.0-svar.',
    ac: 'Anrop till POST /api/mcp med en giltig JSON-RPC 2.0-payload returnerar status 200 och ett JSON-svar med fältet "jsonrpc": "2.0". Verktygslistan matchar lib/mcp/server.ts.',
    vm: 'Enhetstester i tests/unit/mcp-http.test.ts plus manuell verifiering med scripts/dev-curl.sh mot /api/mcp.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.interoperabilitet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.apiUtbyte, ID.pkg.grundSystem],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.INT,
    desc: 'Inloggning ska ske via OIDC-integration mot Keycloak med backchannel-utbyte i /api/auth/callback.',
    ac: 'Lyckad OIDC-flow mot dev-realmen kravhantering-dev resulterar i en sessionscookie och redirect till önskad URL. Felaktig state eller code rejekteras med felmeddelande.',
    vm: 'Integrationstester med oidc-mock samt manuell test mot lokal Keycloak via docker-compose.idp.yml.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.akthet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.sso, ID.pkg.infosak],
    norm: [ID.norm.oidcCore, ID.norm.rfc6749, ID.norm.rfc9700],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.INT,
    desc: 'REST API:er för krav och kravunderlag ska finnas under /api/requirements respektive /api/specifications och stödja CRUD enligt dokumentationen.',
    ac: 'GET, POST, PATCH och DELETE fungerar enligt specifikation och returnerar dokumenterade statuskoder. Felresponser följer ett gemensamt JSON-felschema.',
    vm: 'Vitest enhetstester per route samt scripts/dev-curl.sh för manuell verifiering.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.funkKorrekthet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.apiUtbyte, ID.pkg.grundSystem],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.INT,
    desc: 'Utvecklare ska kunna anropa skyddade API:er lokalt via scripts/dev-curl.sh som återanvänder cachad sessionscookie.',
    ac: 'scripts/dev-curl.sh -s /api/auth/me returnerar 200 med användarprofil efter en första körning som triggat inloggning. Cookie-jar lagras under .auth/<user>.cookies.',
    vm: 'Manuell körning enligt docs/auth-developer-workflow.md plus skript-test under scripts/__tests__/.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.anvandbarhet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.apiUtbyte],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.INT,
    desc: 'Utvecklarverktyget scripts/dev-login.mjs ska kunna hämta en sessionscookie mot dev-realmen utan interaktiv prompt.',
    ac: 'Med standardanvändaren ada.admin/devpass utför scriptet en fullständig OIDC-inloggning, persisterar cookie-jar och stödjer --force för att tvinga ny inloggning.',
    vm: 'Manuell körning samt automatiserad rökig integration via Playwright-konfiguration som använder samma cookie-jar.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.anvandbarhet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.apiUtbyte],
    norm: [],
    item: ID.itemStatus.implementerad,
  },
  // ====== SÄK – Säkerhet (5) ======
  {
    area: ID.area.SAK,
    desc: 'RequirementVersion ska skyddas med optimistisk samtidighetskontroll via fältet revisionToken.',
    ac: 'Vid uppdatering av en version krävs att klientens revisionToken matchar databasens; en ej matchande token returnerar 409 Conflict utan att data ändras.',
    vm: 'Enhetstester av lib/dal/requirements.ts som verifierar konfliktbeteendet plus integrationstester av PATCH /api/requirements/:id.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.integritet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.infosak, ID.pkg.versionshantering],
    norm: [ID.norm.asvs],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.SAK,
    desc: 'Skyddade routes ska returnera 302 till /api/auth/login när giltig session saknas, aldrig läcka data.',
    ac: 'Anrop utan giltig sessionscookie mot t.ex. /api/requirements eller /api/specifications returnerar 302 mot /api/auth/login med originalvägen i parametern returnTo.',
    vm: 'Integrationstester med scripts/dev-curl.sh utan cookie-jar samt enhetstester av middleware-matchningen.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.konfidentialitet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.infosak],
    norm: [ID.norm.asvs, ID.norm.iso27001],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.SAK,
    desc: 'OIDC-callback ska validera state-cookie och PKCE-verifier för att förhindra CSRF och kodinjektion.',
    ac: 'Anrop till /api/auth/callback utan eller med felaktig state-cookie eller PKCE-verifier rejekteras med 400 och loggas som säkerhetshändelse.',
    vm: 'Enhetstester i tests/unit/auth-csrf.test.ts samt tests/unit/auth-callback-audit.test.ts.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.akthet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.infosak, ID.pkg.sso],
    norm: [ID.norm.oidcCore, ID.norm.rfc9700],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.SAK,
    desc: 'Applikationen får inte använda native confirm(), alert() eller window.confirm(); endast den centrala useConfirmModal får visa bekräftelser.',
    ac: 'Statisk analys finner inga anrop till window.confirm/alert/native confirm i komponenter eller routes; alla bekräftelser går via components/ConfirmModal.',
    vm: 'Lint-regel/grep-kontroll i CI samt enhetstester av confirm-modal.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.skyddAnvFel,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.anvandbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.SAK,
    desc: 'Hemligheter ska laddas från .env-filer och valideras vid bygg- och dev-start via dotenv:check.',
    ac: 'npm run dotenv:check failar om obligatoriska variabler saknas eller har platsmarkörer som "changeme".',
    vm: 'Körning av npm run dotenv:check i CI samt manuell verifiering med medvetet trasig .env.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.konfidentialitet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.infosak, ID.pkg.driftTillg],
    norm: [ID.norm.asvs],
    item: ID.itemStatus.verifierad,
  },

  // ====== IDN – Identitet (3) ======
  {
    area: ID.area.IDN,
    desc: 'Inloggning ska följa OIDC Authorization Code-flödet med PKCE.',
    ac: 'Auth-konfigurationen kräver code_challenge_method=S256 och code_challenge i auth-anropet; access- och id-token hämtas via backchannel mot token-endpointen.',
    vm: 'Enhetstester i tests/unit/auth-config.test.ts samt manuell verifiering mot dev-realmen.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.akthet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.sso, ID.pkg.infosak],
    norm: [ID.norm.oidcCore, ID.norm.rfc6749, ID.norm.rfc9700],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.IDN,
    desc: 'Komponenten AuthMenu ska visa inloggad användares namn och e-post samt länk för utloggning.',
    ac: 'AuthMenu renderar förnamn, efternamn och e-post från sessionen; klick på utloggningslänk anropar /api/auth/logout och rensar sessionscookie.',
    vm: 'Enhetstester i tests/unit/auth-menu.test.tsx samt manuell granskning i utvecklingsmiljö.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.sjalvbeskrivning,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.sso, ID.pkg.anvandbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.IDN,
    desc: 'Sessionen ska innehålla användarens HSA-id när det levereras som claim från IdP.',
    ac: 'Vid lyckad inloggning där OIDC-claim hsaIdentifier finns persisteras värdet i sessionen och exponeras via /api/auth/me. Saknas claim sätts fältet till null.',
    vm: 'Enhetstester i tests/unit/auth-hsa-id.test.ts samt manuell test med en testanvändare som har/saknar claim.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.akthet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.sso],
    norm: [ID.norm.oidcCore],
    item: ID.itemStatus.implementerad,
  },

  // ====== BEH – Behörighet (3) ======
  {
    area: ID.area.BEH,
    desc: 'Åtkomst till olika operationer ska styras av roller (admin, reviewer, editor, viewer) via lib/requirements/auth.ts.',
    ac: 'En användare utan reviewer-roll kan inte godkänna eller avslå en granskning; försök returnerar 403 utan att förändra data.',
    vm: 'Enhetstester i tests/unit/auth-roles.test.ts samt scripts/dev-curl.sh-baserade test mot olika dev-användare.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.ansvarsskyldighet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.behorighet, ID.pkg.infosak],
    norm: [ID.norm.iso27001, ID.norm.asvs],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.BEH,
    desc: 'Endast användare med admin-roll ska kunna nå CRUD-administrationen för referensdata.',
    ac: 'CrudAdminPanel renderas inte för icke-admin; tillhörande API-routes returnerar 403 om anroparen saknar admin-rollen.',
    vm: 'Enhetstester i tests/unit/crud-admin-panel.test.tsx och tests/unit/admin-* route-tester.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.konfidentialitet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.behorighet],
    norm: [ID.norm.iso27001],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.BEH,
    desc: 'Granskningsbeslut (godkänn/avslå) på krav och avvikelser får endast utföras av reviewer eller admin.',
    ac: 'Försök från övriga roller returnerar 403; lyckade beslut loggas med beslutande aktör.',
    vm: 'Enhetstester i tests/quality/functional.test.ts samt tests/unit/auth-roles.test.ts.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.ansvarsskyldighet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.behorighet, ID.pkg.sparbarhet],
    norm: [ID.norm.iso27001],
    item: ID.itemStatus.verifierad,
  },

  // ====== PRE – Prestanda (3) ======
  {
    area: ID.area.PRE,
    desc: 'Kravlistan ska kunna rendera minst tusen rader utan att blockera UI:t mer än 100 ms vid scroll.',
    ac: 'RequirementsTable använder paginering eller virtuell scroll så att initial rendering är klar inom 1 sekund för 1000 rader på en utvecklingslaptop.',
    vm: 'Playwright integrationstest tests/integration/requirements-table-resize.spec.ts samt manuell mätning.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.tidsbeteende,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.molndrift, ID.pkg.anvandbarhet],
    norm: [],
    item: ID.itemStatus.implementerad,
  },
  {
    area: ID.area.PRE,
    desc: 'Listvyn ska stödja paginering och kolumnfilter via lib/requirements/list-view.ts.',
    ac: 'Användarens valda kolumner och filter persisteras i URL eller lagring och återställs vid återbesök; tomt filterresultat visar tydligt meddelande.',
    vm: 'Enhetstester i tests/unit/requirement-list-view.test.ts och tests/unit/requirements-table.test.tsx.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.anvandbarhet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.anvandbarhet, ID.pkg.grundSystem],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.PRE,
    desc: 'Initial sidladdning för kravunderlagsöversikten ska vara under 2 sekunder i utvecklingsmiljö med seedad databas.',
    ac: 'Mätning i utvecklingsmiljö visar TTFB under 1 sekund och Largest Contentful Paint under 2 sekunder för /sv/requirements/specifications/KH.',
    vm: 'Manuell mätning med Playwright trace samt CI-kontroll av Next.js build-output storlek.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.tidsbeteende,
    risk: ID.risk.medel,
    test: false,
    pkg: [ID.pkg.anvandbarhet, ID.pkg.driftTillg],
    norm: [],
    item: ID.itemStatus.pagaende,
  },
  // ====== ANV – Användbarhet (5) ======
  {
    area: ID.area.ANV,
    desc: 'ConfirmModal ska kunna förankras nära den knapp som triggade dialogen via anchorEl-parametern.',
    ac: 'När anchorEl skickas placeras dialogen som en popover relativt knappen; utan anchorEl visas en centrerad modal.',
    vm: 'Enhetstester i tests/unit/confirm-modal.test.tsx samt manuell granskning i utvecklingsmiljö.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.anvandbarhet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.anvandbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.ANV,
    desc: 'Komponenten HelpPanel ska ge kontextuell hjälp per vy och fält som kan öppnas och stängas av användaren.',
    ac: 'HelpPanel renderas på vyer enligt help-panel.instructions.md, dess innehåll översätts via i18n och tangentbordsfokus återgår till triggerelementet vid stängning.',
    vm: 'Enhetstester av HelpPanel-komponenten samt manuell granskning av hjälpknapparna i applikationen.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.hjalpmedelsanpassning,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.anvandbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.ANV,
    desc: 'StatusStepper ska visa kravets livscykelflöde med tydligt aktuellt steg och tillåtna nästa steg.',
    ac: 'Aktuell status framgår visuellt och i text; steg som inte är tillåtna från nuvarande status är visuellt nedtonade och har aria-disabled.',
    vm: 'Enhetstester av StatusStepper samt visuell verifiering på kravdetaljvyn.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.sjalvbeskrivning,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.anvandbarhet, ID.pkg.versionshantering],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.ANV,
    desc: 'Mörkt och ljust tema ska kunna växlas via ThemeToggle och persisteras per användare.',
    ac: 'Användarens val sparas i localStorage och återställs vid laddning; växling mellan teman uppdaterar applikationen utan omladdning.',
    vm: 'Enhetstester av ThemeToggle och ThemeRootSync.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.anpassningsbarhet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.anvandbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.ANV,
    desc: 'Komponenten FieldLabelWithHelp ska visa en hjälpikon med popover bredvid varje fält med definierad hjälptext.',
    ac: 'Fält som har hjälptext renderar ikonen; ikonen är tangentbordsfokuserbar och visar hjälpen vid Enter eller klick.',
    vm: 'Enhetstester av FieldLabelWithHelp samt komponentintegration i RequirementForm.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.hjalpmedelsanpassning,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.anvandbarhet, ID.pkg.tillganglighet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },

  // ====== TIL – Tillgänglighet (3) ======
  {
    area: ID.area.TIL,
    desc: 'Användarvända ytor ska uppfylla WCAG 2.2 nivå AA.',
    ac: 'Automatisk tillgänglighetsanalys (axe eller motsvarande) på primära vyer rapporterar inga AA-överträdelser; manuell granskning av tangentbordsnavigering bekräftar fokusordning.',
    vm: 'Automatiserad axe-körning i Playwright samt manuell granskning enligt ui-ux.instructions.md.',
    cat: ID.cat.verksamhet,
    type: ID.type.ickefunk,
    qc: ID.qc.tillganglighet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.tillganglighet, ID.pkg.anvandbarhet],
    norm: [ID.norm.wcag22, ID.norm.en301549],
    item: ID.itemStatus.implementerad,
  },
  {
    area: ID.area.TIL,
    desc: 'HTML-rotelementet ska ha korrekt lang-attribut per vald locale.',
    ac: 'För /sv/* sätts lang="sv" och för /en/* sätts lang="en" på <html>; ändring av locale uppdaterar attributet.',
    vm: 'Enhetstester av layout/Root samt Playwright-test som inspekterar HTML-attributet.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.tillganglighet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.tillganglighet],
    norm: [ID.norm.wcag22],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.TIL,
    desc: 'Developer Mode-overlayen är ett utvecklarverktyg och undantas från krav på WCAG-touch-target och mobilresponsivitet.',
    ac: 'Developer Mode-chips renderas kompakt på desktop; dokumentation och tester anger uttryckligen undantaget.',
    vm: 'Manuell verifiering enligt docs/developer-mode-overlay.md samt enhetstester av DeveloperModeProvider.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.anpassningsbarhet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.sparbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },

  // ====== LAG – Lagring (3) ======
  {
    area: ID.area.LAG,
    desc: 'Krav ska versioneras via tabellen requirement_versions med inkrementellt versionsnummer per krav.',
    ac: 'Varje publicerad redigering skapar en ny version; tidigare versioner finns kvar och kan visas via VersionHistory.',
    vm: 'Enhetstester i tests/quality/functional.test.ts och tests/unit/version-history.test.tsx.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.testbarhet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.versionshantering, ID.pkg.sparbarhet],
    norm: [ID.norm.iso25010],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.LAG,
    desc: 'Krav ska kunna mjukraderas via flaggan is_archived så att de inte längre dyker upp i standardlistor.',
    ac: 'Mjukraderade krav exkluderas från GET /api/requirements som standard men kan inkluderas via parametern includeArchived=true.',
    vm: 'Enhetstester av lib/dal/requirements.ts samt route-tester.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.aterstallningsbarhet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.versionshantering],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.LAG,
    desc: 'Arkivering ska kunna initieras (archive_initiated_at) och fullbordas (archived_at) som två steg.',
    ac: 'Initiering kan ångras (cancelArchiving) före fullbordan; fullbordad arkivering låser kravet från redigering.',
    vm: 'Enhetstester av initiateArchiving/approveArchiving/cancelArchiving i lib/dal/requirements.ts.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.ansvarsskyldighet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.versionshantering, ID.pkg.sparbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  // ====== LOG – Loggning (3) ======
  {
    area: ID.area.LOG,
    desc: 'Spårbarhet på en RequirementVersion ska omfatta createdAt, editedAt, publishedAt, archivedAt och createdBy.',
    ac: 'Alla fyra tidsfält samt createdBy är populerade enligt livscykelreglerna; värdena exponeras i version­historiken och kravdetaljen.',
    vm: 'Enhetstester i tests/quality/functional.test.ts samt manuell verifiering i UI:t.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.ansvarsskyldighet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.sparbarhet, ID.pkg.versionshantering],
    norm: [ID.norm.iso27001],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.LOG,
    desc: 'Developer Mode ska visa en overlay som identifierar källfil, ID och version per komponent.',
    ac: 'När Developer Mode är aktivt visas en chips-/badge-overlay på utvecklingsmiljö med källfilsnamn och versionsnummer; overlayen är osynlig i produktionsmoden.',
    vm: 'Enhetstester i tests/unit/developer-mode-provider.test.tsx samt manuell verifiering enligt docs/developer-mode-overlay.md.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.analyserbarhet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.sparbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.LOG,
    desc: 'Statusändringar för underlagsposter ska spåras via fältet status_updated_at.',
    ac: 'Vid ändring av specification_item_status_id sätts status_updated_at till aktuellt datum; tidigare värde går att läsa via versionshistoriken på kravunderlagsposten.',
    vm: 'Enhetstester av lib/dal/requirements-specifications.ts och DAL-tester av updateSpecificationItemFields.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.ansvarsskyldighet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.sparbarhet],
    norm: [ID.norm.iso27001],
    item: ID.itemStatus.verifierad,
  },

  // ====== DRF – Drift (5) ======
  {
    area: ID.area.DRF,
    desc: 'Applikationen ska kunna self-hostas på en Next.js 16 standalone-runtime utan beroende på Vercel-specifika tjänster.',
    ac: 'next.config.ts producerar en standalone-build; ingen kod refererar till Vercel-specifika API:er som @vercel/* utöver byggverktyg.',
    vm: 'Enhetstester i tests/unit/build-target.test.ts samt manuell körning av next start mot byggd output.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.installerbarhet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.driftTillg],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.DRF,
    desc: 'Node-version ska vara pinnad via .nvmrc och matcha angiven version i package.json engines.',
    ac: '.nvmrc innehåller den dokumenterade Node-LTS-versionen; package.json engines-fält matchar samma major-version.',
    vm: 'Lint-skript scripts/check-port.js och npm run check verifierar; manuell granskning av .nvmrc.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.installerbarhet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.driftTillg],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.DRF,
    desc: 'Lokal utveckling ska kunna starta en SQL Server-instans via docker-compose.sqlserver.yml.',
    ac: 'Compose-filen startar mssql-container med dokumenterade portar och lösenord; npm-script provisionerar databasen och kör migrationer.',
    vm: 'Manuell körning enligt docs/sql-server-developer-workflow.md samt enhetstester i scripts/__tests__/db-sqlserver-admin.test.mjs.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.installerbarhet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.driftTillg],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.DRF,
    desc: 'Lokal utveckling ska kunna starta Keycloak som identitetsleverantör via docker-compose.idp.yml.',
    ac: 'Compose-filen startar Keycloak med dev-realmen kravhantering-dev förladdad; standardanvändarna ada.admin och rita.reviewer kan logga in.',
    vm: 'Manuell körning enligt docs/auth-developer-workflow.md plus oidc-mock-baserade tester.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.installerbarhet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.driftTillg, ID.pkg.sso],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.DRF,
    desc: 'Repot ska tillhandahålla en reproducerbar dev container via .devcontainer/.',
    ac: '.devcontainer/devcontainer.json definierar Node, Git, gh och nödvändiga features; uppstart genom VS Code Dev Containers ger samma toolchain som CI.',
    vm: 'Manuell verifiering enligt docs/github-codespaces.md.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.installerbarhet,
    risk: ID.risk.lag,
    test: false,
    pkg: [ID.pkg.driftTillg],
    norm: [],
    item: ID.itemStatus.verifierad,
  },

  // ====== DAT – Data (4) ======
  {
    area: ID.area.DAT,
    desc: 'TypeORM-migrationer under typeorm/migrations/ ska vara enda källan för databasens DDL.',
    ac: 'Inga ad hoc-DDL-skript förekommer utanför typeorm/migrations/; CI verifierar att schemat efter migrationer matchar entiteterna.',
    vm: 'CI-jobb som kör npm run typeorm:migration:check (eller motsvarande) plus manuell granskning vid PR.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.testbarhet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.driftTillg, ID.pkg.versionshantering],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.DAT,
    desc: 'Seed-data via typeorm/seed.mjs ska vara deterministisk och idempotent.',
    ac: 'Upprepad körning av seed mot tom databas ger identiskt innehåll; rader infogas endast om primärnyckeln saknas.',
    vm: 'Enhetstester i tests/unit/seed-* samt körning av seed två gånger i utvecklingsmiljö.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.testbarhet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.DAT,
    desc: 'Lagringsstacken ska vara SQL Server-only enligt database-schema.instructions.md.',
    ac: 'Inga sqlite-, mysql- eller postgres-drivare finns i package.json; entitetsdefinitioner använder endast SQL Server-kompatibla typer.',
    vm: 'Granskning av package.json och lib/typeorm/entities/* samt CI-build mot SQL Server.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.interoperabilitet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.grundSystem],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.DAT,
    desc: 'Tabell- och kolumnnamn ska följa snake_case enligt database-schema.instructions.md.',
    ac: 'Migrationer och entiteter använder snake_case; PR-granskning säkerställer regelefterlevnad.',
    vm: 'Statisk grep-kontroll i CI samt manuell granskning vid PR.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.modularitet,
    risk: ID.risk.lag,
    test: false,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  // ====== KVA – Kvalitetssäkring (5) ======
  {
    area: ID.area.KVA,
    desc: 'npm run check ska köra hela kvalitetssviten (type-check, lint, format, spell, dotenv, tests).',
    ac: 'Kommandot kör de delar som anges i package.json:s check-skript och failar vid fel i någon delsteg.',
    vm: 'Manuell körning av npm run check och CI-pipeline.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.testbarhet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.KVA,
    desc: 'Vitest ska användas för enhets- och integrationstester under tests/unit och tests/integration.',
    ac: 'vitest.config.ts inkluderar relevanta mappar; npm run test producerar grön körning vid ren checkout.',
    vm: 'CI-körning av npm run test plus täckningsrapport.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.testbarhet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.KVA,
    desc: 'Playwright ska användas för end-to-end-test mot dev-, prodlika- och guide-konfigurationer.',
    ac: 'playwright.config.ts, playwright.prodlike.config.ts och playwright.guide.config.ts startar respektive scenarion och rapporterar resultat under playwright-report*-mapparna.',
    vm: 'CI-körning samt manuell körning enligt docs/auth-developer-workflow.md.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.testbarhet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.implementerad,
  },
  {
    area: ID.area.KVA,
    desc: 'cspell.jsonc ska upprätthålla stavnings-policy för kod, dokumentation och översättningar.',
    ac: 'npm run spell:check failar vid okända ord; tillåtna domänord lever i cspell-ordboken.',
    vm: 'CI-körning av spell-check.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.testbarhet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.KVA,
    desc: 'tests/quality/QUALITY.md utgör kravkontrakt för livscykel-invarianter och ska valideras av tests/quality/functional.test.ts.',
    ac: 'Varje scenario i QUALITY.md har en motsvarande assertion i functional.test.ts; testerna är gröna i CI.',
    vm: 'CI-körning av npm run test:quality.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.testbarhet,
    risk: ID.risk.hog,
    test: true,
    pkg: [ID.pkg.testKvalitet, ID.pkg.versionshantering],
    norm: [ID.norm.iso25010],
    item: ID.itemStatus.verifierad,
  },

  // ====== SPR – Språkstöd (2) ======
  {
    area: ID.area.SPR,
    desc: 'Applikationen ska stödja svenska och engelska via next-intl med översättningar i messages/sv.json och messages/en.json.',
    ac: 'Båda språken har komplett uppsättning nycklar; saknad nyckel triggar lint- eller test-fel.',
    vm: 'Enhetstester av översättningskomplettering samt manuell verifiering i UI:t.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.inkludering,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.tillganglighet, ID.pkg.anvandbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.SPR,
    desc: 'Komponenten LanguageSwitcher ska byta locale utan att förlora navigationskontext.',
    ac: 'Vid byte från /sv/<path> till /en/<path> bibehålls path och query-parametrar.',
    vm: 'Enhetstest av LanguageSwitcher samt Playwright-test som navigerar mellan locales.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.anvandbarhet,
    risk: ID.risk.lag,
    test: true,
    pkg: [ID.pkg.anvandbarhet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },

  // ====== RAP – Rapportering (3) ======
  {
    area: ID.area.RAP,
    desc: 'Systemet ska kunna producera PDF-export av krav och kravunderlag via components/reports/pdf och lib/reports.',
    ac: 'PDF-exporten innehåller kravens id, beskrivning, status, version, kravunderlagskoppling samt rapport-metadata; exporten är reproducerbar för samma indata.',
    vm: 'Enhetstester av lib/reports samt manuell granskning av genererad PDF.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.funkAndamalsenlighet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.grundSystem, ID.pkg.sparbarhet],
    norm: [],
    item: ID.itemStatus.implementerad,
  },
  {
    area: ID.area.RAP,
    desc: 'Utskriftsvänliga vyer ska finnas under components/reports/print för att stödja pappersrapportering.',
    ac: 'Print-vyer är formaterade utan navigation/footer och visar all relevant kravdata; @media print-regler aktiverar layouten.',
    vm: 'Manuell utskrift och Playwright-snapshot.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.funkAndamalsenlighet,
    risk: ID.risk.lag,
    test: false,
    pkg: [ID.pkg.grundSystem],
    norm: [],
    item: ID.itemStatus.implementerad,
  },
  {
    area: ID.area.RAP,
    desc: 'Reports-modulen ska producera en kravunderlagsrapport med kravinklusion och status per post.',
    ac: 'Rapporten listar varje requirement_specification_item med uniqueId, beskrivning, status och länkad version; sortering följer underlagets ordning.',
    vm: 'Enhetstester av lib/reports/data och manuell verifiering på underlaget KH.',
    cat: ID.cat.verksamhet,
    type: ID.type.funk,
    qc: ID.qc.funkKorrekthet,
    risk: ID.risk.medel,
    test: true,
    pkg: [ID.pkg.sparbarhet, ID.pkg.grundSystem],
    norm: [],
    item: ID.itemStatus.implementerad,
  },

  // ====== UTV – Utvecklingsmiljö (3) ======
  {
    area: ID.area.UTV,
    desc: 'Skills under .github/skills/ ska tillhandahålla återanvändbara arbetsflöden för automatiserade agenter.',
    ac: 'Varje skill har en SKILL.md med beskrivning, indata och utdata; skills synkroniseras till Codex via scripts enligt sync-codex-skills-skillen.',
    vm: 'Manuell granskning av skills samt körning av sync-codex-skills.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.modularitet,
    risk: ID.risk.lag,
    test: false,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.UTV,
    desc: 'Instructions under .github/instructions/ ska styra automatiserad kodassistans per applyTo-mönster.',
    ac: 'Varje instruktionsfil har applyTo-pattern och påverkar agentens beteende endast för matchande filer; copilot-instructions.md refererar till samtliga filer.',
    vm: 'Manuell granskning samt PR-checks som verifierar applyTo-syntax.',
    cat: ID.cat.it,
    type: ID.type.funk,
    qc: ID.qc.andringsbarhet,
    risk: ID.risk.lag,
    test: false,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  {
    area: ID.area.UTV,
    desc: 'AGENTS.md och .github/copilot-instructions.md ska definiera gemensamma regler för agenter och Copilot.',
    ac: 'Båda filerna existerar i repots root respektive .github/ och innehåller projektets stack, kommandon och styrande principer; uppdateringar görs synkroniserat.',
    vm: 'Manuell granskning vid förändring.',
    cat: ID.cat.it,
    type: ID.type.ickefunk,
    qc: ID.qc.andringsbarhet,
    risk: ID.risk.lag,
    test: false,
    pkg: [ID.pkg.testKvalitet],
    norm: [],
    item: ID.itemStatus.verifierad,
  },
  // KRAV-INSERT-MARKER (do not remove; used during file authoring)
]

// Two specifications: the main "Kravhantering" specification (KH) and a smaller PoC
// specification (KH-POC) that holds a curated subset for demonstrating the Införande
// lifecycle.
const DOGFOOD_SPECIFICATIONS = [
  {
    id: SPEC_KH,
    uniqueId: 'KH',
    name: 'Kravhantering',
    responsibility: ID.specRespArea.forvaltningsobjekt,
    impl: ID.specImpl.utveckling,
    lifecycle: ID.specLifecycle.utveckling,
    businessNeeds:
      'Standardiserat kravarbete för plattformen Kravhantering: ett gemensamt kravunderlag som beskriver vad applikationen själv ska kunna, så att förändringar prövas mot ett dogfooded kravregister.',
  },
  {
    id: SPEC_KH_POC,
    uniqueId: 'KH-POC',
    name: 'Kravhantering PoC införande',
    responsibility: ID.specRespArea.projekt,
    impl: ID.specImpl.utveckling,
    lifecycle: ID.specLifecycle.inforande,
    businessNeeds:
      'Pilot-införande av Kravhantering hos en första förvaltning. Underlaget pekar ut den delmängd Krav som krävs för PoC och innehåller underlagslokala varianter där PoC behöver justerade acceptanskriterier.',
  },
]

// Business-needs references attached to each specification
const DOGFOOD_NEEDS_REFS = [
  // KH
  {
    spec: SPEC_KH,
    text: 'Spårbarhet mellan krav, version och kravunderlag — Kravhantering ska kunna styras av sina egna krav.',
  },
  {
    spec: SPEC_KH,
    text: 'Stöd för MCP-baserad AI-assistans mot kravregistret för granskning, sökning och rapportering.',
  },
  {
    spec: SPEC_KH,
    text: 'Standardiserat kravarbete för svensk offentlig sektor med stöd för normhänvisningar och svenskspråkiga texter.',
  },
  {
    spec: SPEC_KH,
    text: 'Reproducerbar utvecklings- och driftmiljö så att teamet kan dogfooda applikationen lokalt.',
  },
  // KH-POC
  {
    spec: SPEC_KH_POC,
    text: 'PoC-införande hos en pilotförvaltning för att validera kravregistrets arbetssätt på riktig data.',
  },
  {
    spec: SPEC_KH_POC,
    text: 'Begränsad omfattning under införande — endast de Krav som behövs för PoC ingår.',
  },
]

// Specification-local requirements: PoC-specific tweaks of a few Krav. Each entry
// references the dogfood Krav by its 0-based index in DOGFOOD_KRAV (so the
// builder can resolve the matching requirement_area_id, category, etc.).
// kravIdx must point to a Krav that is also linked into KH-POC via
// DOGFOOD_KH_POC_INDEXES below.
const DOGFOOD_SPECIFICATION_LOCALS = [
  {
    spec: SPEC_KH_POC,
    kravIdx: 3, // ARK middleware krav
    descSuffix:
      ' I PoC-leveransen accepteras även anonymt åtkomliga hälso-endpoints under /api/health/*.',
    acSuffix:
      ' Under PoC tillåts dessutom undantag för en intern statussida som visas utan inloggning.',
    note: 'PoC-undantag för statussida tas bort i full produktionssättning.',
    needsRefOffset: 4, // index into DOGFOOD_NEEDS_REFS (KH-POC: PoC-införande)
    item: ID.itemStatus.avviken,
  },
  {
    spec: SPEC_KH_POC,
    kravIdx: 23, // ANV ConfirmModal anchor krav
    descSuffix:
      ' I PoC ska minst destruktiva åtgärder (radera, arkivera) använda anchorEl-positioneringen.',
    acSuffix:
      ' Övriga ja/nej-bekräftelser får i PoC visas som centrerad modal utan anchorEl.',
    note: 'PoC-anpassning för att minska scope; full anchorEl-täckning planeras i nästa version.',
    needsRefOffset: 5, // KH-POC: Begränsad omfattning
    item: ID.itemStatus.pagaende,
  },
]

// Indexes (0-based into DOGFOOD_KRAV) of Krav that should also appear in
// KH-POC. Picked to cover de Krav som faktiskt är nödvändiga för en PoC:
// arkitektur, integration, säkerhet, identitet, behörighet, lagring/version,
// loggning, drift, data, kvalitetssäkring, rapportering.
const DOGFOOD_KH_POC_INDEXES = [
  0, // ARK App Router
  3, // ARK middleware
  4, // INT MCP
  5, // INT OIDC
  6, // INT REST CRUD
  9, // SÄK revisionToken
  10, // SÄK 302 redirect
  14, // IDN OIDC PKCE
  17, // BEH roller
  23, // ANV ConfirmModal anchor
  31, // LAG versionering
  34, // LOG spårbarhet
  37, // DRF self-host
  39, // DRF SQL Server compose
  42, // DAT migrationer
  46, // KVA npm run check
  53, // RAP PDF
]

export {
  AREA_PREFIX_BY_ID,
  DOGFOOD_AREAS,
  DOGFOOD_KH_POC_INDEXES,
  DOGFOOD_KRAV,
  DOGFOOD_NEEDS_REFS,
  DOGFOOD_NORMS,
  DOGFOOD_OWNERS,
  DOGFOOD_REQUIREMENT_PACKAGES,
  DOGFOOD_SPECIFICATION_LOCALS,
  DOGFOOD_SPECIFICATIONS,
  ID,
  NEEDS_REF_ID_BASE,
  REQUIREMENT_ID_BASE,
  SEED_TS,
  SPEC_KH,
  SPEC_KH_POC,
  SPECIFICATION_ITEM_ID_BASE,
  SPECIFICATION_LOCAL_ID_BASE,
  VERSION_ID_BASE,
}
