// @vitest-environment node
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { generateStatusIconAliases } from '../generate-status-icon-aliases.mjs'

describe('status icon alias exports', () => {
  it('exports only aliases outside the canonical catalog in deterministic order', () => {
    const result = generateStatusIconAliases(
      ['wifi', 'x-circle', 'alert-triangle', 'x-circle', 'arrow-down-a-z'],
      ['Wifi', 'CircleX', 'TriangleAlert', 'ArrowDownAZ'],
    )
    expect(result).toBe(
      [
        '// Generated by scripts/generate-status-icon-aliases.mjs. Do not edit.',
        '// cspell:disable',
        'export {',
        '  AlertTriangle,',
        '  XCircle,',
        "} from 'lucide-react'",
        '',
      ].join('\n'),
    )
  })

  it('handles catalogs with no aliases', () => {
    expect(generateStatusIconAliases(['wifi'], ['Wifi'])).toContain(
      "export {\n} from 'lucide-react'",
    )
  })

  it('rejects names that cannot safely become JavaScript exports', () => {
    expect(() => generateStatusIconAliases(['bad/name'], [])).toThrow(
      'Invalid status icon export name',
    )
  })

  it('keeps the generated exports aligned with the installed package', async () => {
    const { icons } = await import('lucide-react')
    const { default: imports } = await import(
      'lucide-react/dynamicIconImports.mjs'
    )
    const source = readFileSync(
      new URL(
        '../../lib/icons/status-icon-aliases.generated.ts',
        import.meta.url,
      ),
      'utf8',
    )
    expect(source).toBe(
      generateStatusIconAliases(Object.keys(imports), Object.keys(icons)),
    )
  })
})
