export const SPECIFICATION_LIFECYCLE_STATUS_PROCUREMENT_ID = 1
export const SPECIFICATION_LIFECYCLE_STATUS_IMPLEMENTATION_ID = 2
export const SPECIFICATION_LIFECYCLE_STATUS_DEVELOPMENT_ID = 3
export const SPECIFICATION_LIFECYCLE_STATUS_MANAGEMENT_ID = 4

export const PROGRESS_REPORT_SPECIFICATION_LIFECYCLE_STATUS_IDS = [
  SPECIFICATION_LIFECYCLE_STATUS_IMPLEMENTATION_ID,
  SPECIFICATION_LIFECYCLE_STATUS_DEVELOPMENT_ID,
] as const
